/**
 * Authoritative Static Syllabus Architecture for Quizzer
 * Exclusively dedicated to Rajasthan GK across 5 Canonical Subjects and 70 Master Topics.
 * Conforms to AGENTS.md syllabus contract, RPSC 2nd Grade Paper 1 and RSMSSB CET standards.
 */

export interface StaticSubTopic {
  id: string;
  titleHindi: string;
  titleEnglish: string;
  keyPoints?: string[];
}

export interface StaticTopic {
  id: number; // Canonical Topic ID: 1 - 70
  slug: string;
  name: string;
  nameHindi: string;
  subjectSlug: string;
  subjectHindi: string;
  examScope: "2nd_grade" | "cet" | "both";
  isCommon: boolean;
  commonKey?: string;
  subTopics: StaticSubTopic[];
}

export interface StaticSubject {
  slug: string;
  name: string;
  nameHindi: string;
  order: number;
  description: string;
  topicCount: number;
  topicIdRange: [number, number];
}

export const CANONICAL_SUBJECTS: StaticSubject[] = [
  {
    slug: "rajasthan-general-knowledge-geography",
    name: "Rajasthan General Knowledge & Geography",
    nameHindi: "राजस्थान सामान्य ज्ञान एवं भूगोल",
    order: 1,
    description: "राजस्थान का सामान्य ज्ञान, भौतिक स्वरूप, भूगोल, जलवायु, नदियाँ, झीलें, कृषि, वन एवं खनिज संसाधन",
    topicCount: 15,
    topicIdRange: [1, 15],
  },
  {
    slug: "rajasthan-history",
    name: "Rajasthan History",
    nameHindi: "राजस्थान का इतिहास",
    order: 2,
    description: "राजस्थान का संपूर्ण इतिहास: प्राचीन सभ्यताएँ, राजपूत राजवंश, दिल्ली सल्तनत एवं मुग़ल संबंध, 1857 की क्रांति, प्रजामंडल, किसान व आदिवासी आंदोलन, एकीकरण एवं प्रमुख व्यक्तित्व",
    topicCount: 21,
    topicIdRange: [32, 52],
  },
  {
    slug: "rajasthan-art-culture",
    name: "Rajasthan Art & Culture",
    nameHindi: "राजस्थान कला एवं संस्कृति",
    order: 3,
    description: "मेले, त्योहार, रीति-रिवाज, वेशभूषा, स्थापत्य, चित्रकला, हस्तशिल्प, लोक देवता, संगीत, नृत्य, भाषा एवं साहित्य",
    topicCount: 16,
    topicIdRange: [16, 31],
  },
  {
    slug: "rajasthan-polity-administration",
    name: "Rajasthan Polity & Administration",
    nameHindi: "राजस्थान राजव्यवस्था / प्रशासन",
    order: 4,
    description: "राज्य प्रशासन, राज्यपाल, मुख्यमंत्री, मंत्रिपरिषद, विधानमंडल, उच्च न्यायालय, जिला प्रशासन, पंचायती राज व सांविधानिक आयोग",
    topicCount: 18,
    topicIdRange: [53, 70],
  },
];

export const CANONICAL_TOPICS: StaticTopic[] = [
  // ─── A. राजस्थान सामान्य ज्ञान एवं भूगोल (1 - 15) ───
  {
    id: 1,
    slug: "general-knowledge-of-rajasthan",
    name: "General Knowledge of Rajasthan",
    nameHindi: "राजस्थान का सामान्य ज्ञान",
    subjectSlug: "rajasthan-general-knowledge-geography",
    subjectHindi: "राजस्थान सामान्य ज्ञान एवं भूगोल",
    examScope: "both",
    isCommon: true,
    commonKey: "raj-gk-general",
    subTopics: [
      { id: "sub-1-1", titleHindi: "स्थिति, विस्तार एवं सीमावर्ती राज्य/देश", titleEnglish: "Geographical Location & International/State Boundaries" },
      { id: "sub-1-2", titleHindi: "संभाग एवं जिलों का पुनर्गठन", titleEnglish: "Administrative Divisions & Reorganized Districts" },
      { id: "sub-1-3", titleHindi: "राजस्थान के राज्य प्रतीक (पुष्प, वृक्ष, पशु, पक्षी, खेल, गीत)", titleEnglish: "State Symbols of Rajasthan" },
      { id: "sub-1-4", titleHindi: "प्रथम पदाधिकारी एवं प्रमुख व्यक्तित्व", titleEnglish: "First Dignitaries & Historical Firsts" },
    ],
  },
  {
    id: 2,
    slug: "physical-features-geography-rajasthan",
    name: "Physical Features and Geography of Rajasthan",
    nameHindi: "राजस्थान का भौतिक स्वरूप एवं भूगोल",
    subjectSlug: "rajasthan-general-knowledge-geography",
    subjectHindi: "राजस्थान सामान्य ज्ञान एवं भूगोल",
    examScope: "both",
    isCommon: true,
    commonKey: "raj-geo-physical",
    subTopics: [
      { id: "sub-2-1", titleHindi: "थार का मरुस्थल (शुष्क व अर्द्धशुष्क मैदान, बालुका स्तूप, लाठी सीरीज)", titleEnglish: "Thar Desert & Dune Formations" },
      { id: "sub-2-2", titleHindi: "अरावली पर्वतीय प्रदेश (उत्तरी, मध्य, दक्षिणी अरावली, चोटियाँ व दर्रे)", titleEnglish: "Aravalli Range & Mountain Passes" },
      { id: "sub-2-3", titleHindi: "पूर्वी मैदान (बनास बेसिन, छप्पन का मैदान, चंबल बीहड़)", titleEnglish: "Eastern Plain & Basins" },
      { id: "sub-2-4", titleHindi: "हाड़ौती का पठार (दक्कन लावा पठार, विंध्यन कगार भूमि)", titleEnglish: "Hadoti Plateau & Vindhyan Scarplands" },
    ],
  },
  {
    id: 3,
    slug: "climate-of-rajasthan",
    name: "Climate of Rajasthan",
    nameHindi: "राजस्थान की जलवायु",
    subjectSlug: "rajasthan-general-knowledge-geography",
    subjectHindi: "राजस्थान सामान्य ज्ञान एवं भूगोल",
    examScope: "both",
    isCommon: true,
    commonKey: "raj-geo-climate",
    subTopics: [
      { id: "sub-3-1", titleHindi: "ऋतु चक्र एवं स्थानीय पवने (लू, मावठ, पुरवइयाँ)", titleEnglish: "Seasons & Local Wind Phenomena" },
      { id: "sub-3-2", titleHindi: "कोपेन का जलवायु वर्गीकरण (BWhw, BShw, Cwg, Aw)", titleEnglish: "Koeppen Climate Classification" },
      { id: "sub-3-3", titleHindi: "थॉर्नथवेट व ट्रिवार्था का जलवायु वर्गीकरण", titleEnglish: "Thornthwaite & Trewartha Systems" },
      { id: "sub-3-4", titleHindi: "वर्षा का वितरण एवं 50 सेमी व 25 सेमी समवर्षा रेखाएँ", titleEnglish: "Rainfall Isohyets & Drought Patterns" },
    ],
  },
  {
    id: 4,
    slug: "population-and-census-of-rajasthan",
    name: "Population and Census of Rajasthan",
    nameHindi: "राजस्थान की जनसंख्या एवं जनगणना",
    subjectSlug: "rajasthan-general-knowledge-geography",
    subjectHindi: "राजस्थान सामान्य ज्ञान एवं भूगोल",
    examScope: "both",
    isCommon: true,
    commonKey: "raj-geo-demography",
    subTopics: [
      { id: "sub-4-1", titleHindi: "जनसंख्या वृद्धि दर, घनत्व एवं वितरण (2011 जनगणना)", titleEnglish: "Growth Rate & Population Density" },
      { id: "sub-4-2", titleHindi: "लिंगानुपात एवं 0-6 आयु वर्ग शिशु लिंगानुपात", titleEnglish: "Sex Ratio & Child Sex Ratio" },
      { id: "sub-4-3", titleHindi: "साक्षरता दर (कुल, पुरुष एवं महिला साक्षरता विश्लेषण)", titleEnglish: "Literacy Trends & Disparities" },
      { id: "sub-4-4", titleHindi: "अनुसूचित जाति (SC) एवं अनुसूचित जनजाति (ST) जनसांख्यिकी", titleEnglish: "SC/ST Demographics & Tribal Distribution" },
    ],
  },
  {
    id: 5,
    slug: "soils-of-rajasthan",
    name: "Soils of Rajasthan",
    nameHindi: "राजस्थान की मृदा",
    subjectSlug: "rajasthan-general-knowledge-geography",
    subjectHindi: "राजस्थान सामान्य ज्ञान एवं भूगोल",
    examScope: "both",
    isCommon: true,
    commonKey: "raj-geo-soil",
    subTopics: [
      { id: "sub-5-1", titleHindi: "पारंपरिक मिट्टियों के प्रकार (रेतीली, लाल-पीली, काली, जलोढ़, भूरी)", titleEnglish: "Traditional Soil Classifications" },
      { id: "sub-5-2", titleHindi: "वैज्ञानिक वर्गीकरण (Aridisols, Alfisols, Entisols, Inceptisols, Vertisols)", titleEnglish: "USDA Soil Taxonomy in Rajasthan" },
      { id: "sub-5-3", titleHindi: "मृदा अपरदन (जल व वायु अपरदन) एवं सेम की समस्या", titleEnglish: "Soil Erosion & Waterlogging (Sem)" },
      { id: "sub-5-4", titleHindi: "मृदा सुधार एवं उर्वरता प्रबंधन उपाय", titleEnglish: "Soil Fertility & Conservation Measures" },
    ],
  },
  {
    id: 6,
    slug: "drainage-system-rivers-and-lakes-rajasthan",
    name: "Drainage System, Rivers and Lakes of Rajasthan",
    nameHindi: "राजस्थान का अपवाह तंत्र, नदियाँ एवं झीलें",
    subjectSlug: "rajasthan-general-knowledge-geography",
    subjectHindi: "राजस्थान सामान्य ज्ञान एवं भूगोल",
    examScope: "both",
    isCommon: true,
    commonKey: "raj-geo-rivers",
    subTopics: [
      { id: "sub-6-1", titleHindi: "अरब सागरीय अपवाह तंत्र (लूणी, माही, साबरमती, पश्चिमी बनास)", titleEnglish: "Arabian Sea Drainage (Luni, Mahi, Sabarmati)" },
      { id: "sub-6-2", titleHindi: "बंगाल की खाड़ी अपवाह तंत्र (चंबल, बनास, बाणगंगा, कालीसिंध)", titleEnglish: "Bay of Bengal Drainage (Chambal, Banas)" },
      { id: "sub-6-3", titleHindi: "आंतरिक अपवाह तंत्र (कांतली, काकनेय, साबी, घग्घर, मेंथा)", titleEnglish: "Inland Drainage Rivers" },
      { id: "sub-6-4", titleHindi: "मीठे पानी की प्रमुख झीलें (जयसमंद, राजसमंद, पिछोला, नक्की, आनासागर)", titleEnglish: "Freshwater Lakes" },
      { id: "sub-6-5", titleHindi: "खारे पानी की झीलें (सांभर, पचपदरा, डीडवाना, लूणकरणसर)", titleEnglish: "Saline Lakes of Rajasthan" },
    ],
  },
  {
    id: 7,
    slug: "irrigation-projects-dams-water-management",
    name: "Irrigation Projects, Dams and Water Management",
    nameHindi: "राजस्थान की सिंचाई परियोजनाएँ, बाँध एवं जल प्रबंधन",
    subjectSlug: "rajasthan-general-knowledge-geography",
    subjectHindi: "राजस्थान सामान्य ज्ञान एवं भूगोल",
    examScope: "both",
    isCommon: true,
    commonKey: "raj-geo-irrigation",
    subTopics: [
      { id: "sub-7-1", titleHindi: "इंदिरा गांधी नहर परियोजना (IGNP) - मुख्य नहर, शाखाएं व लिफ्ट नहरें", titleEnglish: "Indira Gandhi Canal Project (IGNP)" },
      { id: "sub-7-2", titleHindi: "प्रमुख बांध (राणा प्रताप सागर, बीसलपुर, माही बजाज सागर, जवाई बांध)", titleEnglish: "Major Dams of Rajasthan" },
      { id: "sub-7-3", titleHindi: "ईसरदा, परवन, नर्मदा नहर एवं पूर्वी राजस्थान नहर परियोजना (ERCP)", titleEnglish: "ERCP & Inter-linking Projects" },
      { id: "sub-7-4", titleHindi: "परंपरागत जल संरक्षण प्रणालियाँ (बावड़ी, टांका, जोहड़, खड़ीन, बेरी)", titleEnglish: "Traditional Water Harvesting Techniques" },
    ],
  },
  {
    id: 8,
    slug: "forests-wildlife-sanctuaries-national-parks",
    name: "Forests, Wildlife, Sanctuaries and National Parks",
    nameHindi: "राजस्थान के वन, वन्यजीव, अभयारण्य एवं राष्ट्रीय उद्यान",
    subjectSlug: "rajasthan-general-knowledge-geography",
    subjectHindi: "राजस्थान सामान्य ज्ञान एवं भूगोल",
    examScope: "both",
    isCommon: true,
    commonKey: "raj-geo-vegetation",
    subTopics: [
      { id: "sub-8-1", titleHindi: "वन संपदा एवं राज्य वन रिपोर्ट (आरक्षित, संरक्षित व अवर्गीकृत वन)", titleEnglish: "Forest Classification & ISFR Report" },
      { id: "sub-8-2", titleHindi: "राष्ट्रीय उद्यान (रणथंभौर, केवलादेव घाना, मुकुंदरा हिल्स)", titleEnglish: "National Parks of Rajasthan" },
      { id: "sub-8-3", titleHindi: "टाइगर रिजर्व (रणथंभौर, सरिस्का, मुकुंदरा, रामगढ़ विषधारी, धौलपुर-करौली)", titleEnglish: "Tiger Reserves" },
      { id: "sub-8-4", titleHindi: "प्रमुख वन्यजीव अभयारण्य एवं कंजर्वेशन रिजर्व", titleEnglish: "Sanctuaries & Conservation Reserves" },
      { id: "sub-8-5", titleHindi: "रामसर आर्द्रभूमि स्थल (केवलादेव व सांभर झील)", titleEnglish: "Ramsar Wetland Sites" },
    ],
  },
  {
    id: 9,
    slug: "agriculture-of-rajasthan",
    name: "Agriculture of Rajasthan",
    nameHindi: "राजस्थान की कृषि",
    subjectSlug: "rajasthan-general-knowledge-geography",
    subjectHindi: "राजस्थान सामान्य ज्ञान एवं भूगोल",
    examScope: "both",
    isCommon: true,
    commonKey: "raj-geo-agri",
    subTopics: [
      { id: "sub-9-1", titleHindi: "फसल ऋतुएं: रबी, खरीफ एवं जायद की प्रमुख फसलें", titleEnglish: "Cropping Seasons: Rabi, Kharif & Zaid" },
      { id: "sub-9-2", titleHindi: "कृषि जलवायु खंड (10 Agro-Climatic Zones)", titleEnglish: "10 Agro-Climatic Zones of Rajasthan" },
      { id: "sub-9-3", titleHindi: "नकदी, दलहन, तिलहन व मसाला फसलें (सरसों, ईसबगोल, जीरा, धनिया)", titleEnglish: "Commercial, Oilseed & Spice Crops" },
      { id: "sub-9-4", titleHindi: "जैविक खेती एवं प्रमुख कृषि योजनाएं", titleEnglish: "Organic Farming & Government Schemes" },
    ],
  },
  {
    id: 10,
    slug: "animal-husbandry-of-rajasthan",
    name: "Animal Husbandry of Rajasthan",
    nameHindi: "राजस्थान का पशुपालन",
    subjectSlug: "rajasthan-general-knowledge-geography",
    subjectHindi: "राजस्थान सामान्य ज्ञान एवं भूगोल",
    examScope: "both",
    isCommon: true,
    commonKey: "raj-geo-livestock",
    subTopics: [
      { id: "sub-10-1", titleHindi: "पशुधन गणना (20वीं पशुगणना प्रमुख आंकड़े व रुझान)", titleEnglish: "20th Livestock Census Statistics" },
      { id: "sub-10-2", titleHindi: "गाय, भैंस, भेड़ एवं बकरी की प्रमुख नस्लें व वितरण", titleEnglish: "Major Breeds of Cattle, Sheep, Goat & Camel" },
      { id: "sub-10-3", titleHindi: "राज्य के प्रमुख पशु अनुसंधान एवं प्रजनन केंद्र", titleEnglish: "Breeding & Research Centers" },
      { id: "sub-10-4", titleHindi: "डेयरी विकास कार्यक्रम (RCDF, सरस) एवं ऊन उत्पादन", titleEnglish: "Dairy Co-operatives & Wool Production" },
    ],
  },
  {
    id: 11,
    slug: "mineral-resources-of-rajasthan",
    name: "Mineral Resources of Rajasthan",
    nameHindi: "राजस्थान के खनिज संसाधन",
    subjectSlug: "rajasthan-general-knowledge-geography",
    subjectHindi: "राजस्थान सामान्य ज्ञान एवं भूगोल",
    examScope: "both",
    isCommon: true,
    commonKey: "raj-geo-minerals",
    subTopics: [
      { id: "sub-11-1", titleHindi: "धात्विक खनिज (सीसा-जस्ता, तांबा, लोहा, टंगस्टन, चांदी)", titleEnglish: "Metallic Minerals & Key Mines" },
      { id: "sub-11-2", titleHindi: "अधात्विक खनिज (रॉक फॉस्फेट, जिप्सम, संगमरमर, ग्रेनाइट, चूना पत्थर)", titleEnglish: "Non-Metallic Minerals & Dimension Stones" },
      { id: "sub-11-3", titleHindi: "राजस्थान का एकाधिकार खनिज (वोलास्टोनाइट, जास्पर, गार्नेट, सीसा-जस्ता)", titleEnglish: "Minerals with State Monopoly" },
      { id: "sub-11-4", titleHindi: "पेट्रोलियम एवं हाइड्रोकार्बन बेसिन (बाड़मेर-सांचौर, बीकानेर-नागौर)", titleEnglish: "Petroleum Basins & Oilfields" },
    ],
  },
  {
    id: 12,
    slug: "energy-resources-of-rajasthan",
    name: "Energy Resources of Rajasthan",
    nameHindi: "राजस्थान के ऊर्जा संसाधन",
    subjectSlug: "rajasthan-general-knowledge-geography",
    subjectHindi: "राजस्थान सामान्य ज्ञान एवं भूगोल",
    examScope: "both",
    isCommon: true,
    commonKey: "raj-geo-energy",
    subTopics: [
      { id: "sub-12-1", titleHindi: "सौर ऊर्जा (भड़ला सोलर पार्क, अक्षय ऊर्जा नीति)", titleEnglish: "Solar Energy & Bhadla Solar Park" },
      { id: "sub-12-2", titleHindi: "पवन एवं बायोमास ऊर्जा परियोजनाएं", titleEnglish: "Wind & Biomass Power Projects" },
      { id: "sub-12-3", titleHindi: "तापीय विद्युत संयंत्र (सूरतगढ़, कोटा, छबड़ा, कालीसिंध)", titleEnglish: "Thermal Power Stations" },
      { id: "sub-12-4", titleHindi: "परमाणु ऊर्जा (रावतभाटा RAPS) एवं जल विद्युत", titleEnglish: "Nuclear (Rawatbhata) & Hydro Power" },
    ],
  },
  {
    id: 13,
    slug: "major-industries-of-rajasthan",
    name: "Major Industries of Rajasthan",
    nameHindi: "राजस्थान के प्रमुख उद्योग",
    subjectSlug: "rajasthan-general-knowledge-geography",
    subjectHindi: "राजस्थान सामान्य ज्ञान एवं भूगोल",
    examScope: "both",
    isCommon: true,
    commonKey: "raj-geo-industries",
    subTopics: [
      { id: "sub-13-1", titleHindi: "सूती वस्त्र उद्योग एवं प्रमुख मिलें", titleEnglish: "Textile Industry & Mills" },
      { id: "sub-13-2", titleHindi: "सीमेंट एवं खनिज आधारित भारी उद्योग", titleEnglish: "Cement & Mineral-Based Industries" },
      { id: "sub-13-3", titleHindi: "कृषि आधारित उद्योग (चीनी, तेल मिलें, एग्रो फूड पार्क)", titleEnglish: "Agro-Processing & Food Parks" },
      { id: "sub-13-4", titleHindi: "रीको (RIICO), RFC एवं औद्योगिक विकास क्षेत्र (SEZ, DMIC)", titleEnglish: "RIICO, SEZ & DMIC Corridor" },
    ],
  },
  {
    id: 14,
    slug: "transportation-in-rajasthan",
    name: "Transportation in Rajasthan",
    nameHindi: "राजस्थान का परिवहन",
    subjectSlug: "rajasthan-general-knowledge-geography",
    subjectHindi: "राजस्थान सामान्य ज्ञान एवं भूगोल",
    examScope: "both",
    isCommon: true,
    commonKey: "raj-geo-transport",
    subTopics: [
      { id: "sub-14-1", titleHindi: "सड़क परिवहन (राष्ट्रीय राजमार्ग, राज्य राजमार्ग एवं एक्सप्रेसवे)", titleEnglish: "Road Network & Expressways" },
      { id: "sub-14-2", titleHindi: "रेलवे नेटवर्क (उत्तर पश्चिम रेलवे जोन, उप-मंडल)", titleEnglish: "Railway Zones & Major Routes" },
      { id: "sub-14-3", titleHindi: "वायु परिवहन (प्रमुख हवाई अड्डे एवं उड़ान योजना)", titleEnglish: "Airports & Civil Aviation" },
      { id: "sub-14-4", titleHindi: "जयपुर मेट्रो एवं दिल्ली-मुंबई एक्सप्रेसवे परियोजना", titleEnglish: "Jaipur Metro & High-Speed Corridors" },
    ],
  },
  {
    id: 15,
    slug: "tourism-in-rajasthan",
    name: "Tourism in Rajasthan",
    nameHindi: "राजस्थान का पर्यटन",
    subjectSlug: "rajasthan-general-knowledge-geography",
    subjectHindi: "राजस्थान सामान्य ज्ञान एवं भूगोल",
    examScope: "both",
    isCommon: true,
    commonKey: "raj-geo-tourism",
    subTopics: [
      { id: "sub-15-1", titleHindi: "प्रमुख पर्यटन सर्किट (मरु सर्किट, ढूंढाड़, मेवाड़, हाड़ौती)", titleEnglish: "Tourist Circuits of Rajasthan" },
      { id: "sub-15-2", titleHindi: "आरटीडीसी (RTDC) एवं पर्यटन नीतियां", titleEnglish: "RTDC & State Tourism Policies" },
      { id: "sub-15-3", titleHindi: "हेरिटेज पर्यटन एवं पैलेस ऑन व्हील्स", titleEnglish: "Heritage Tourism & Luxury Trains" },
      { id: "sub-15-4", titleHindi: "धार्मिक, सांस्कृतिक एवं पारिस्थितिकी पर्यटन स्थल", titleEnglish: "Pilgrimage, Eco & Rural Tourism" },
    ],
  },

  // ─── B. राजस्थान कला एवं संस्कृति (16 - 31) ───
  {
    id: 16,
    slug: "fairs-of-rajasthan",
    name: "Fairs of Rajasthan",
    nameHindi: "राजस्थान के मेले",
    subjectSlug: "rajasthan-art-culture",
    subjectHindi: "राजस्थान कला एवं संस्कृति",
    examScope: "both",
    isCommon: true,
    commonKey: "raj-cult-fairs",
    subTopics: [
      { id: "sub-16-1", titleHindi: "प्रमुख धार्मिक व सांस्कृतिक मेले (पुष्कर, रामदेवरा, बेणेश्वर, खाटूश्यामजी)", titleEnglish: "Major Religious Fairs" },
      { id: "sub-16-2", titleHindi: "प्रसिद्ध पशु मेले (तिलवाड़ा, परबतसर, झालरापाटन, गोगामेड़ी)", titleEnglish: "State Livestock Fairs" },
      { id: "sub-16-3", titleHindi: "जनजातीय मेले (बेणेश्वर धाम, सीताबाड़ी मेला)", titleEnglish: "Tribal Fairs & Gathering" },
      { id: "sub-16-4", titleHindi: "मेले, तिथियाँ एवं संबंधित लोक मान्यताएं", titleEnglish: "Tithis & Calendar Timings of Fairs" },
    ],
  },
  {
    id: 17,
    slug: "festivals-of-rajasthan",
    name: "Festivals of Rajasthan",
    nameHindi: "राजस्थान के त्योहार",
    subjectSlug: "rajasthan-art-culture",
    subjectHindi: "राजस्थान कला एवं संस्कृति",
    examScope: "both",
    isCommon: true,
    commonKey: "raj-cult-festivals",
    subTopics: [
      { id: "sub-17-1", titleHindi: "हिन्दू पंचांग अनुसार प्रमुख त्योहार (गणगौर, कजली तीज, छोटी तीज)", titleEnglish: "Hindu Calendar Festivals (Gangaur, Teej)" },
      { id: "sub-17-2", titleHindi: "जैन, मुस्लिम, सिख एवं ईसाई धर्म के प्रमुख त्योहार", titleEnglish: "Jain, Muslim, Sikh & Christian Festivals" },
      { id: "sub-17-3", titleHindi: "स्थानीय लोकोत्सव एवं सांस्कृतिक महोत्सव (मरु महोत्सव, थार महोत्सव)", titleEnglish: "Desert Festival & Regional Utsavs" },
      { id: "sub-17-4", titleHindi: "त्योहारों से जुड़े विशेष पकवान एवं रीति-रिवाज", titleEnglish: "Traditions & Ritual Foods of Festivals" },
    ],
  },
  {
    id: 18,
    slug: "customs-and-traditions-of-rajasthan",
    name: "Customs and Traditions of Rajasthan",
    nameHindi: "राजस्थान की रीति-रिवाज एवं परंपराएँ",
    subjectSlug: "rajasthan-art-culture",
    subjectHindi: "राजस्थान कला एवं संस्कृति",
    examScope: "both",
    isCommon: true,
    commonKey: "raj-cult-customs",
    subTopics: [
      { id: "sub-18-1", titleHindi: "जन्म एवं बाल्यकाल संस्कार (जात-कर्म, नामकरण, चूड़ाकर्म)", titleEnglish: "Birth & Childhood Rites" },
      { id: "sub-18-2", titleHindi: "विवाह संबंधी रस्में एवं परंपराएँ (तोरण, सामैला, बिंदोली, पहरावणी)", titleEnglish: "Marriage Customs & Rituals" },
      { id: "sub-18-3", titleHindi: "मृत्यु संस्कार (मोसर, जोसर, सांतरवाड़ा, फूल चुनना)", titleEnglish: "Funeral Rites & Mourning Traditions" },
      { id: "sub-18-4", titleHindi: "सामाजिक प्रथाएँ व कुप्रथा उन्मूलन (सती, डाकन, समाधि, बाल विवाह)", titleEnglish: "Abolition of Social Evils" },
    ],
  },
  {
    id: 19,
    slug: "costumes-and-ornaments-of-rajasthan",
    name: "Costumes and Ornaments of Rajasthan",
    nameHindi: "राजस्थान की वेशभूषा एवं आभूषण",
    subjectSlug: "rajasthan-art-culture",
    subjectHindi: "राजस्थान कला एवं संस्कृति",
    examScope: "both",
    isCommon: true,
    commonKey: "raj-cult-costumes",
    subTopics: [
      { id: "sub-19-1", titleHindi: "पुरुष वेशभूषा (पगड़ी/साफा, अंगरखी, धोती, चुगा, पछेवड़ा)", titleEnglish: "Men's Traditional Attire & Turbans" },
      { id: "sub-19-2", titleHindi: "महिला वेशभूषा (घाघरा, कुर्ती-कांचली, ओढ़नी, पोमचा, लहरिया)", titleEnglish: "Women's Attire & Dupattas" },
      { id: "sub-19-3", titleHindi: "सिर व मस्तक के आभूषण (शीशफूल, रखड़ी, बोरला, मेमंद, टीका)", titleEnglish: "Head & Forehead Ornaments" },
      { id: "sub-19-4", titleHindi: "नाक, कान, गला एवं हाथ-पैरों के आभूषण (नथ, टिमणिया, चोंप, कंदोरा, तगड़ी)", titleEnglish: "Neck, Nose, Ear & Limb Ornaments" },
    ],
  },
  {
    id: 20,
    slug: "architecture-and-monuments-of-rajasthan",
    name: "Architecture and Monuments of Rajasthan",
    nameHindi: "राजस्थान की स्थापत्य कला एवं वास्तुकला",
    subjectSlug: "rajasthan-art-culture",
    subjectHindi: "राजस्थान कला एवं संस्कृति",
    examScope: "both",
    isCommon: true,
    commonKey: "raj-cult-architecture",
    subTopics: [
      { id: "sub-20-1", titleHindi: "यूनेस्को विश्व धरोहर दुर्ग (चित्तौड़गढ़, कुंभलगढ़, रणथंभौर, गागरोन, आमेर, जैसलमेर)", titleEnglish: "6 UNESCO Hill Forts" },
      { id: "sub-20-2", titleHindi: "अन्य प्रमुख दुर्ग (मेहरानगढ़, तारागढ़, जूनागढ़, भटनेर, सिवाना, जालौर)", titleEnglish: "Other Historic Forts" },
      { id: "sub-20-3", titleHindi: "प्रमुख मंदिर स्थापत्य (महामारु शैली, नागर शैली, देलवाड़ा जैन मंदिर)", titleEnglish: "Temple Architecture & Maha-Maru Style" },
      { id: "sub-20-4", titleHindi: "हवेलियाँ, छतरियाँ एवं ऐतिहासिक बावड़ियाँ (चांद बावड़ी, पटवों की हवेली)", titleEnglish: "Havelis, Cenotaphs & Stepwells" },
    ],
  },
  {
    id: 21,
    slug: "painting-schools-of-rajasthan",
    name: "Painting Schools of Rajasthan",
    nameHindi: "राजस्थान की चित्रकला शैलियाँ",
    subjectSlug: "rajasthan-art-culture",
    subjectHindi: "राजस्थान कला एवं संस्कृति",
    examScope: "both",
    isCommon: true,
    commonKey: "raj-cult-paintings",
    subTopics: [
      { id: "sub-21-1", titleHindi: "मेवाड़ चित्रशैली (चावंड, नाथद्वारा पिछवाई, प्रमुख चित्रकार)", titleEnglish: "Mewar School & Pichwai Art" },
      { id: "sub-21-2", titleHindi: "मारवाड़ एवं किशनगढ़ चित्रशैली (बणी-ठणी, निहालचंद, जोधपुर शैली)", titleEnglish: "Marwar & Kishangarh (Bani Thani)" },
      { id: "sub-21-3", titleHindi: "ढूंढाड़ चित्रशैली (आमेर, जयपुर, अलवर, शेखावाटी भित्ति चित्र)", titleEnglish: "Dhundhar School & Shekhawati Frescoes" },
      { id: "sub-21-4", titleHindi: "हाड़ौती चित्रशैली (बूंदी - शिकार व पशु-पक्षी दृश्य, कोटा शैली)", titleEnglish: "Hadoti School (Bundi & Kota)" },
    ],
  },
  {
    id: 22,
    slug: "handicrafts-and-crafts-of-rajasthan",
    name: "Handicrafts and Crafts of Rajasthan",
    nameHindi: "राजस्थान के हस्तशिल्प एवं हस्तकलाएँ",
    subjectSlug: "rajasthan-art-culture",
    subjectHindi: "राजस्थान कला एवं संस्कृति",
    examScope: "both",
    isCommon: true,
    commonKey: "raj-cult-handicrafts",
    subTopics: [
      { id: "sub-22-1", titleHindi: "थेवा कला (प्रतापगढ़), मीनाकारी व कुंदन कार्य (जयपुर)", titleEnglish: "Thewa Art & Meenakari" },
      { id: "sub-22-2", titleHindi: "ब्लू पॉटरी, ब्लैक पॉटरी एवं कागजी पॉटरी", titleEnglish: "Pottery Styles: Blue, Black & Kagzi" },
      { id: "sub-22-3", titleHindi: "बंधेज, अजरक प्रिंट, दाबू प्रिंट, मलीर प्रिंट व सांगानेरी प्रिंट", titleEnglish: "Textile Prints & Bandhej Dyeing" },
      { id: "sub-22-4", titleHindi: "मोलेला टेराकोटा, उस्ता कला (बीकानेर) व काष्ठ कला (बस्सी)", titleEnglish: "Usta Art, Terracotta & Woodcraft" },
    ],
  },
  {
    id: 23,
    slug: "folk-deities-and-goddesses-of-rajasthan",
    name: "Folk Deities and Goddesses of Rajasthan",
    nameHindi: "राजस्थान के लोक देवता एवं लोक देवियाँ",
    subjectSlug: "rajasthan-art-culture",
    subjectHindi: "राजस्थान कला एवं संस्कृति",
    examScope: "both",
    isCommon: true,
    commonKey: "raj-cult-deities",
    subTopics: [
      { id: "sub-23-1", titleHindi: "पंचपीर (पाबूजी, रामदेवजी, गोगाजी, मेहाजी मांगलिया, हड़बूजी)", titleEnglish: "Panchpir of Rajasthan" },
      { id: "sub-23-2", titleHindi: "तेजाजी, देवनारायणजी, वीर कल्लाजी एवं मल्लीनाथजी", titleEnglish: "Tejaji, Devnarayanji & Veer Kallaji" },
      { id: "sub-23-3", titleHindi: "प्रमुख लोक देवियाँ (करणी माता, जीण माता, शीला देवी, कैला देवी)", titleEnglish: "Prominent Goddesses (Karni Mata, Jeen Mata)" },
      { id: "sub-23-4", titleHindi: "कुलदेवियाँ, लोक मान्यताएं एवं प्रमुख पूजा स्थल / थान", titleEnglish: "Kuldevis & Folk Beliefs" },
    ],
  },
  {
    id: 24,
    slug: "saints-sects-religious-traditions-rajasthan",
    name: "Saints Sects and Religious Traditions of Rajasthan",
    nameHindi: "राजस्थान के संत, संप्रदाय एवं धार्मिक परंपराएँ",
    subjectSlug: "rajasthan-art-culture",
    subjectHindi: "राजस्थान कला एवं संस्कृति",
    examScope: "both",
    isCommon: true,
    commonKey: "raj-cult-saints",
    subTopics: [
      { id: "sub-24-1", titleHindi: "विश्नोई संप्रदाय एवं जांभोजी (29 नियम, पर्यावरण संरक्षण)", titleEnglish: "Bishnoi Sect & Jambhoji" },
      { id: "sub-24-2", titleHindi: "जसनाथी संप्रदाय एवं अग्नि नृत्य (कतरियासर)", titleEnglish: "Jasnathi Sect & Fire Dance" },
      { id: "sub-24-3", titleHindi: "दादू दयाल एवं दादूपंथ (नरेना, वाणियाँ, प्रमुख शिष्य)", titleEnglish: "Dadu Dayal & Dadupanth" },
      { id: "sub-24-4", titleHindi: "रामस्नेही संप्रदाय की 4 शाखाएं (शाहपुरा, रेण, सींथल, खेड़ापा)", titleEnglish: "Ramsnehi Sect 4 Branches" },
      { id: "sub-24-5", titleHindi: "मीराबाई, संत धन्ना, पीपा, चरणदास एवं लालदासी संप्रदाय", titleEnglish: "Meerabai & Bhakti Movement Saints" },
    ],
  },
  {
    id: 25,
    slug: "folk-music-and-folk-songs-of-rajasthan",
    name: "Folk Music and Folk Songs of Rajasthan",
    nameHindi: "राजस्थान का लोक संगीत एवं लोकगीत",
    subjectSlug: "rajasthan-art-culture",
    subjectHindi: "राजस्थान कला एवं संस्कृति",
    examScope: "both",
    isCommon: true,
    commonKey: "raj-cult-music",
    subTopics: [
      { id: "sub-25-1", titleHindi: "प्रमुख लोकगीत (केसरिया बालम, मूमल, कुरजां, गोरबंद, पणिहारी)", titleEnglish: "Classic Folk Songs & Themes" },
      { id: "sub-25-2", titleHindi: "संगीत घराने एवं गायकी शैलियाँ (मांगणियार, लंगा, कालबेलिया, मांड)", titleEnglish: "Music Gharanas & Singing Communities" },
      { id: "sub-25-3", titleHindi: "तत एवं सुषिर वाद्य यंत्र (रावणहत्था, कामायचा, सारंगी, अलगोजा, पूंगी)", titleEnglish: "String & Wind Musical Instruments" },
      { id: "sub-25-4", titleHindi: "अवनद्ध एवं घन वाद्य यंत्र (ढोल, मांदल, नगाड़ा, खड़ताल, मंजीरा)", titleEnglish: "Percussion & Metal Instruments" },
    ],
  },
  {
    id: 26,
    slug: "folk-dances-of-rajasthan",
    name: "Folk Dances of Rajasthan",
    nameHindi: "राजस्थान के लोक नृत्य",
    subjectSlug: "rajasthan-art-culture",
    subjectHindi: "राजस्थान कला एवं संस्कृति",
    examScope: "both",
    isCommon: true,
    commonKey: "raj-cult-dances",
    subTopics: [
      { id: "sub-26-1", titleHindi: "राज्य नृत्य: घूमर एवं इसके प्रकार (लूर, झूमरियो)", titleEnglish: "Ghoomar - State Dance" },
      { id: "sub-26-2", titleHindi: "व्यावसायिक लोक नृत्य (तेरहताली, भवाई, कच्ची घोड़ी, चरी)", titleEnglish: "Commercial & Acrobatic Dances" },
      { id: "sub-26-3", titleHindi: "जनजातीय नृत्य (भीलों के गवरी/राई, गैर, नेजा; गरासियों के वालर, लूर)", titleEnglish: "Tribal Dances (Bhil, Garasia, Sahariya)" },
      { id: "sub-26-4", titleHindi: "क्षेत्रीय लोक नृत्य (गींदड़, चंग, ढोल नृत्य, बम नृत्य, डांग)", titleEnglish: "Regional Dances (Shekhawati, Mewat)" },
    ],
  },
  {
    id: 27,
    slug: "rajasthani-language-and-dialects",
    name: "Rajasthani Language and Dialects",
    nameHindi: "राजस्थानी भाषा एवं बोलियाँ",
    subjectSlug: "rajasthan-art-culture",
    subjectHindi: "राजस्थान कला एवं संस्कृति",
    examScope: "both",
    isCommon: true,
    commonKey: "raj-cult-language",
    subTopics: [
      { id: "sub-27-1", titleHindi: "राजस्थानी भाषा की उत्पत्ति, विकास एवं वर्गीकरण (जॉर्ज ग्रियर्सन)", titleEnglish: "Origins & Grierson's Classification" },
      { id: "sub-27-2", titleHindi: "पश्चिमी राजस्थानी बोलियाँ (मारवाड़ी, मेवाड़ी, वागड़ी, शेखावाटी)", titleEnglish: "Western Dialects (Marwari, Mewari)" },
      { id: "sub-27-3", titleHindi: "पूर्वी व दक्षिणी बोलियाँ (ढूंढाड़ी, हाड़ौती, मेवाती, मालवी, अहिरवाटी)", titleEnglish: "Eastern & Southern Dialects" },
      { id: "sub-27-4", titleHindi: "डिंगल एवं पिंगल शैलियाँ तथा लिपि (मुड़िया/महाजनी)", titleEnglish: "Dingal, Pingal & Muria Script" },
    ],
  },
  {
    id: 28,
    slug: "rajasthani-literature",
    name: "Rajasthani Literature",
    nameHindi: "राजस्थानी साहित्य",
    subjectSlug: "rajasthan-art-culture",
    subjectHindi: "राजस्थान कला एवं संस्कृति",
    examScope: "both",
    isCommon: true,
    commonKey: "raj-cult-literature",
    subTopics: [
      { id: "sub-28-1", titleHindi: "प्राचीन एवं मध्यकालीन साहित्य (रासो, ख्यात, बात, वेली, प्रकाश)", titleEnglish: "Ancient & Medieval Genres" },
      { id: "sub-28-2", titleHindi: "प्रमुख ग्रंथकार (चंद्रबरदाई, नैणसी, सूर्यमल्ल मी मिश्रण, दुरसा आढा)", titleEnglish: "Classic Chroniclers & Court Poets" },
      { id: "sub-28-3", titleHindi: "आधुनिक राजस्थानी साहित्यकार (कन्हैयालाल सेठिया, विजयदान देथा, सीताराम लालस)", titleEnglish: "Modern Authors (Sethia, Detha)" },
      { id: "sub-28-4", titleHindi: "साहित्यिक संस्थाएँ एवं पुरस्कार (राजस्थान साहित्य अकादमी)", titleEnglish: "Literary Academies & Awards" },
    ],
  },
  {
    id: 29,
    slug: "rajasthani-vocabulary",
    name: "Rajasthani Vocabulary",
    nameHindi: "राजस्थानी शब्दावली",
    subjectSlug: "rajasthan-art-culture",
    subjectHindi: "राजस्थान कला एवं संस्कृति",
    examScope: "both",
    isCommon: false,
    subTopics: [
      { id: "sub-29-1", titleHindi: "कृषि, फसल एवं मौसम से संबंधित देशज शब्द", titleEnglish: "Agricultural & Weather Terms" },
      { id: "sub-29-2", titleHindi: "गृहस्थी, औजार एवं पशुपालन संबंधी शब्दावली", titleEnglish: "Household & Pastoral Vocabulary" },
      { id: "sub-29-3", titleHindi: "पारिवारिक रिश्ते-नाते एवं सामाजिक संबोधन शब्द", titleEnglish: "Kinship & Social Terms" },
    ],
  },
  {
    id: 30,
    slug: "rajasthani-idioms-and-proverbs",
    name: "Rajasthani Idioms and Proverbs",
    nameHindi: "राजस्थानी मुहावरे एवं लोकोक्तियाँ",
    subjectSlug: "rajasthan-art-culture",
    subjectHindi: "राजस्थान कला एवं संस्कृति",
    examScope: "both",
    isCommon: true,
    commonKey: "raj-cult-idioms",
    subTopics: [
      { id: "sub-30-1", titleHindi: "प्रचलित राजस्थानी कहावतें एवं उनका व्यावहारिक अर्थ", titleEnglish: "Common Proverbs & Practical Meaning" },
      { id: "sub-30-2", titleHindi: "ऐतिहासिक घटनाओं व व्यक्तियों पर आधारित लोकोक्तियाँ", titleEnglish: "Historical Idioms & Anecdotes" },
      { id: "sub-30-3", titleHindi: "मौसम, शकुन-अपशकुन एवं नीतिपरक कहावतें", titleEnglish: "Weather & Moral Proverbs" },
    ],
  },
  {
    id: 31,
    slug: "nicknames-of-major-places-in-rajasthan",
    name: "Nicknames of Major Places in Rajasthan",
    nameHindi: "राजस्थान के प्रमुख स्थानों के उपनाम",
    subjectSlug: "rajasthan-art-culture",
    subjectHindi: "राजस्थान कला एवं संस्कृति",
    examScope: "both",
    isCommon: true,
    commonKey: "raj-cult-nicknames",
    subTopics: [
      { id: "sub-31-1", titleHindi: "प्रमुख नगरों के भौगोलिक व सांस्कृतिक उपनाम (गुलाबी नगरी, स्वर्ण नगरी)", titleEnglish: "City Nicknames (Pink City, Sun City)" },
      { id: "sub-31-2", titleHindi: "राजस्थान का शिमला, कश्मीर, गौरव, पेरिस, वेनिस आदि की उपाधियाँ", titleEnglish: "Comparative Geographic Titles" },
      { id: "sub-31-3", titleHindi: "प्राचीन एवं मध्यकालीन नाम (विराटनगर, शूरसेन, जांगलदेश, माध्यमिका)", titleEnglish: "Historical Place Names & Regions" },
    ],
  },

  // ─── C. राजस्थान प्राचीन एवं मध्यकालीन इतिहास (32 - 43) ───
  {
    id: 32,
    slug: "ancient-civilizations-archaeological-sites",
    name: "Ancient Civilizations and Archaeological Sites of Rajasthan",
    nameHindi: "राजस्थान की प्राचीन सभ्यताएँ एवं पुरातात्विक स्थल",
    subjectSlug: "rajasthan-ancient-medieval-history",
    subjectHindi: "राजस्थान प्राचीन एवं मध्यकालीन इतिहास",
    examScope: "both",
    isCommon: true,
    commonKey: "raj-hist-ancient-sites",
    subTopics: [
      { id: "sub-32-1", titleHindi: "कालीबंगा सभ्यता (हनुमानगढ़, घग्घर नदी, अमलानंद घोष, जूते खेत)", titleEnglish: "Kalibangan Site & Excavations" },
      { id: "sub-32-2", titleHindi: "आहड़ सभ्यता (ताम्रवती नगरी, उदयपुर, बेड़च नदी, गोरे-कोठे)", titleEnglish: "Ahar Civilization (Tamravati)" },
      { id: "sub-32-3", titleHindi: "गणेश्वर सभ्यता (नीम का थाना, कांतली नदी, ताम्र संचयी संस्कृति)", titleEnglish: "Ganeshwar Copper Culture" },
      { id: "sub-32-4", titleHindi: "बैराठ सभ्यता (विराटनगर, मौर्यकालीन अवशेष, भाब्रू शिलालेख)", titleEnglish: "Bairath & Ashokan Inscriptions" },
      { id: "sub-32-5", titleHindi: "अन्य प्रमुख स्थल (बागोर, बालाथल, सुनारी, गिलूण्ड, रेड)", titleEnglish: "Bagor, Balathal, Gilund & Rairh" },
    ],
  },
  {
    id: 33,
    slug: "sources-of-rajasthan-history",
    name: "Sources of Rajasthan History",
    nameHindi: "राजस्थान के इतिहास के स्रोत",
    subjectSlug: "rajasthan-ancient-medieval-history",
    subjectHindi: "राजस्थान प्राचीन एवं मध्यकालीन इतिहास",
    examScope: "both",
    isCommon: true,
    commonKey: "raj-hist-sources",
    subTopics: [
      { id: "sub-33-1", titleHindi: "शिलालेख एवं प्रशस्तियाँ (बिजौलिया, कीर्तिस्तंभ, कुंभलगढ़, राजप्रशस्ति)", titleEnglish: "Inscriptions & Eulogies (Prashastis)" },
      { id: "sub-33-2", titleHindi: "ताम्रपत्र एवं दानपत्र (बड़वा, पुर, चीरवा)", titleEnglish: "Copper Plates & Land Grants" },
      { id: "sub-33-3", titleHindi: "सिक्के एवं मुद्राशास्त्र (गधिया सिक्के, विजयशाही, तमंचाशाही)", titleEnglish: "Coins & Princely Numismatics" },
      { id: "sub-33-4", titleHindi: "फारसी एवं राजस्थानी तवारीखें तथा अभिलेखागार सामग्री", titleEnglish: "Persian Chronicles & State Archives" },
    ],
  },
  {
    id: 34,
    slug: "mahajanapadas-ancient-political-history",
    name: "Mahajanapadas and Ancient Political History of Rajasthan",
    nameHindi: "राजस्थान के महाजनपद एवं प्राचीन राजनीतिक इतिहास",
    subjectSlug: "rajasthan-ancient-medieval-history",
    subjectHindi: "राजस्थान प्राचीन एवं मध्यकालीन इतिहास",
    examScope: "both",
    isCommon: false,
    subTopics: [
      { id: "sub-34-1", titleHindi: "मत्स्य महाजनपद (विराटनगर राजधानी, कुरु संबंध)", titleEnglish: "Matsya Mahajanapada" },
      { id: "sub-34-2", titleHindi: "शूरसेन एवं सीवी जनपद (माध्यमिका/नगरी राजधानी)", titleEnglish: "Shurasena & Sibi Janapada" },
      { id: "sub-34-3", titleHindi: "मालव, योद्धेय एवं अर्जुनायन गणराज्य", titleEnglish: "Malava, Yaudheya & Arjunayana Republics" },
      { id: "sub-34-4", titleHindi: "मौर्य, गुप्त एवं हूणों का शासन प्रभाव", titleEnglish: "Mauryan, Gupta & Huna Influence" },
    ],
  },
  {
    id: 35,
    slug: "rajput-period-in-rajasthan",
    name: "Rajput Period in Rajasthan",
    nameHindi: "राजस्थान का राजपूत काल",
    subjectSlug: "rajasthan-ancient-medieval-history",
    subjectHindi: "राजस्थान प्राचीन एवं मध्यकालीन इतिहास",
    examScope: "both",
    isCommon: true,
    commonKey: "raj-hist-dynasties",
    subTopics: [
      { id: "sub-35-1", titleHindi: "राजपूतों की उत्पत्ति के सिद्धांत (अग्निकुंड, सूर्यवंशी, चंद्रवंशी, विदेशी)", titleEnglish: "Theories of Rajput Origins" },
      { id: "sub-35-2", titleHindi: "आरंभिक राजपूत राज्य एवं सामंती व्यवस्था की शुरुआत", titleEnglish: "Early Rajput Kingdoms & Feudalism" },
      { id: "sub-35-3", titleHindi: "अरब आक्रमणों का प्रतिरोध एवं बप्पा रावल की भूमिका", titleEnglish: "Resistance to Early Arab Invasions" },
    ],
  },
  {
    id: 36,
    slug: "guhil-and-guhilot-dynasty-of-mewar",
    name: "Guhil and Guhilot Dynasty of Mewar",
    nameHindi: "मेवाड़ का गुहिल/गुहिलोत वंश",
    subjectSlug: "rajasthan-ancient-medieval-history",
    subjectHindi: "राजस्थान प्राचीन एवं मध्यकालीन इतिहास",
    examScope: "both",
    isCommon: true,
    commonKey: "raj-hist-mewar",
    subTopics: [
      { id: "sub-36-1", titleHindi: "गुहादित्य, बप्पा रावल, जैत्रसिंह एवं भूताला युद्ध", titleEnglish: "Early Rulers & Battle of Bhutala" },
      { id: "sub-36-2", titleHindi: "रावल रतनसिंह, अलाउद्दीन खिलजी का आक्रमण (1303) व प्रथम जौहर", titleEnglish: "Rawal Ratan Singh & 1303 Siege" },
      { id: "sub-36-3", titleHindi: "राणा हम्मीर (विषमघाटी पंचानन), राणा लाखा व महाराणा मोकल", titleEnglish: "Rana Hammir & Foundation of Sisodia" },
      { id: "sub-36-4", titleHindi: "महाराणा कुंभा (विजय स्तंभ, स्थापत्य कला, संगीत ग्रंथ)", titleEnglish: "Maharana Kumbha - Battles & Architecture" },
      { id: "sub-36-5", titleHindi: "राणा सांगा (खानवा, गागरोन, खातोली युद्ध)", titleEnglish: "Rana Sanga & Battle of Khanwa" },
      { id: "sub-36-6", titleHindi: "महाराणा प्रताप (हल्दीघाटी, दिवेर का युद्ध, छापामार रणनीति)", titleEnglish: "Maharana Pratap & Haldighati" },
      { id: "sub-36-7", titleHindi: "अमरसिंह प्रथम (1615 मुगल संधि), राजसिंह एवं चारुमती विवाद", titleEnglish: "Raj Singh & Mewar-Mughal Treaty" },
    ],
  },
  {
    id: 37,
    slug: "kachhwaha-dynasty-of-amer",
    name: "Kachhwaha Dynasty of Amer",
    nameHindi: "आमेर का कछवाहा वंश",
    subjectSlug: "rajasthan-ancient-medieval-history",
    subjectHindi: "राजस्थान प्राचीन एवं मध्यकालीन इतिहास",
    examScope: "both",
    isCommon: true,
    commonKey: "raj-hist-kachhwaha",
    subTopics: [
      { id: "sub-37-1", titleHindi: "दूल्हा राय, भारमल (मुगल अधीनता 1562) व भगवंत दास", titleEnglish: "Early Amer Rulers & Mughal Alliance" },
      { id: "sub-37-2", titleHindi: "मिर्जा राजा मानसिंह प्रथम (हल्दीघाटी, काबुल, बंगाल, उड़ीसा अभियान)", titleEnglish: "Man Singh I - Campaigns & Arts" },
      { id: "sub-37-3", titleHindi: "मिर्जा राजा जयसिंह (पुरंदर की संधि 1665, बिहारी सतसई)", titleEnglish: "Mirza Raja Jai Singh & Treaty of Purandar" },
      { id: "sub-37-4", titleHindi: "सवाई जयसिंह द्वितीय (जयपुर नगर स्थापना, 5 वेधशालाएं/जंतर-मंतर)", titleEnglish: "Sawai Jai Singh II - City & Observatories" },
      { id: "sub-37-5", titleHindi: "सवाई प्रतापसिंह (हवामहल निर्माण) व गंधर्व बाईसी", titleEnglish: "Sawai Pratap Singh & Hawa Mahal" },
    ],
  },
  {
    id: 38,
    slug: "chauhan-dynasty",
    name: "Chauhan Dynasty",
    nameHindi: "चौहान वंश",
    subjectSlug: "rajasthan-ancient-medieval-history",
    subjectHindi: "राजस्थान प्राचीन एवं मध्यकालीन इतिहास",
    examScope: "both",
    isCommon: true,
    commonKey: "raj-hist-chauhan",
    subTopics: [
      { id: "sub-38-1", titleHindi: "शाकंभरी/सांभर के चौहान (वासुदेव, अजयराज, अर्णोराज, विग्रहराज चतुर्थ)", titleEnglish: "Chauhans of Sambhar & Ajmer" },
      { id: "sub-38-2", titleHindi: "पृथ्वीराज चौहान तृतीय (तराइन का प्रथम व द्वितीय युद्ध, दलपंगुल)", titleEnglish: "Prithviraj Chauhan III & Battles of Tarain" },
      { id: "sub-38-3", titleHindi: "रणथंभौर के चौहान (हम्मीर देव चौहान, खिलजी आक्रमण 1301)", titleEnglish: "Hammir Dev of Ranthambore (1301 Siege)" },
      { id: "sub-38-4", titleHindi: "जालौर के चौहान (कान्हड़देव, वीरमदेव, सिवाना व जालौर साका)", titleEnglish: "Kanhad Dev Chauhan of Jalore" },
      { id: "sub-38-5", titleHindi: "हाड़ौती के हाड़ा चौहान एवं सिरोही के देवड़ा चौहान", titleEnglish: "Hada & Deora Chauhan Branches" },
    ],
  },
  {
    id: 39,
    slug: "gurjara-pratihara-dynasty",
    name: "Gurjara Pratihara Dynasty",
    nameHindi: "गुर्जर-प्रतिहार वंश",
    subjectSlug: "rajasthan-ancient-medieval-history",
    subjectHindi: "राजस्थान प्राचीन एवं मध्यकालीन इतिहास",
    examScope: "both",
    isCommon: true,
    commonKey: "raj-hist-pratihara",
    subTopics: [
      { id: "sub-39-1", titleHindi: "हरिश्चंद्र एवं मंडोर शाखा (बाउक व कक्कुका के अभिलेख)", titleEnglish: "Origins & Mandore Branch" },
      { id: "sub-39-2", titleHindi: "भीनमाल/जालौर शाखा (नागभट्ट प्रथम, वत्सराज, त्रिपक्षीय संघर्ष)", titleEnglish: "Bhinmal Branch & Tripartite Struggle" },
      { id: "sub-39-3", titleHindi: "नागभट्ट द्वितीय, मिहिर भोज प्रथम (प्रभास, आदिवराह उपाधि)", titleEnglish: "Nagabhata II & Mihir Bhoja" },
      { id: "sub-39-4", titleHindi: "महेंद्रपाल प्रथम, राजशेखर (कपूरमंजरी, काव्यमीमांसा) व पतन", titleEnglish: "Mahendrapala, Rajashekhara & Decline" },
    ],
  },
  {
    id: 40,
    slug: "rathore-dynasty",
    name: "Rathore Dynasty",
    nameHindi: "राठौड़ वंश",
    subjectSlug: "rajasthan-ancient-medieval-history",
    subjectHindi: "राजस्थान प्राचीन एवं मध्यकालीन इतिहास",
    examScope: "both",
    isCommon: true,
    commonKey: "raj-hist-rathore",
    subTopics: [
      { id: "sub-40-1", titleHindi: "मारवाड़ के राठौड़: राव सीहा, चूंडा, रणमल, राव जोधा (जोधपुर स्थापना)", titleEnglish: "Early Marwar Rulers & Foundation of Jodhpur" },
      { id: "sub-40-2", titleHindi: "राव मालदेव (हशमत वाला शासक, गिरी सुमेल का युद्ध 1544)", titleEnglish: "Rao Maldev & Battle of Giri-Sumel" },
      { id: "sub-40-3", titleHindi: "राव चंद्रसेन (मारवाड़ का प्रताप, भूला-बिसरा राजा)", titleEnglish: "Rao Chandrasen - Resistance to Akbar" },
      { id: "sub-40-4", titleHindi: "वीर दुर्गादास राठौड़ एवं अजीतसिंह (30 वर्षीय संघर्ष)", titleEnglish: "Durgadas Rathore & 30-Year War" },
      { id: "sub-40-5", titleHindi: "बीकानेर के राठौड़: राव बीका, लूणकरण, राव जैतसी, रायसिंह, अनूपसिंह", titleEnglish: "Rathores of Bikaner (Bika, Raisingh)" },
    ],
  },
  {
    id: 41,
    slug: "other-major-dynasties-of-rajasthan",
    name: "Other Major Dynasties of Rajasthan",
    nameHindi: "राजस्थान के अन्य प्रमुख राजवंश",
    subjectSlug: "rajasthan-ancient-medieval-history",
    subjectHindi: "राजस्थान प्राचीन एवं मध्यकालीन इतिहास",
    examScope: "both",
    isCommon: false,
    subTopics: [
      { id: "sub-41-1", titleHindi: "भरतपुर एवं धौलपुर का जाट राजवंश (सूरजमल - जाटों का प्लेटो)", titleEnglish: "Jat Dynasty of Bharatpur (Suraj Mal)" },
      { id: "sub-41-2", titleHindi: "जैसलमेर का भाटी राजवंश (राव जैसल, ढाई साके)", titleEnglish: "Bhati Dynasty of Jaisalmer" },
      { id: "sub-41-3", titleHindi: "टोंक की मुस्लिम नवाब रियासत (अमीर खां पिंडारी)", titleEnglish: "Nawabs of Tonk (Amir Khan Pindari)" },
      { id: "sub-41-4", titleHindi: "करौली का यादव राजवंश एवं हाड़ौती के झाला राजवंश", titleEnglish: "Yadavs of Karauli & Jhalas of Jhalawar" },
    ],
  },
  {
    id: 42,
    slug: "princely-states-and-british-treaties",
    name: "Princely States of Rajasthan and British Treaties",
    nameHindi: "राजस्थान की रियासतें एवं ब्रिटिश संधियाँ",
    subjectSlug: "rajasthan-ancient-medieval-history",
    subjectHindi: "राजस्थान प्राचीन एवं मध्यकालीन इतिहास",
    examScope: "both",
    isCommon: true,
    commonKey: "raj-hist-treaties",
    subTopics: [
      { id: "sub-42-1", titleHindi: "लॉर्ड वेलेजली की सहायक संधि (भरतपुर व अलवर - 1803)", titleEnglish: "Subsidiary Alliances (1803)" },
      { id: "sub-42-2", titleHindi: "लॉर्ड हेस्टिंग्स की आश्रित पार्थक्य संधि (1817-1818)", titleEnglish: "Treaties of Subordinate Cooperation (1817-18)" },
      { id: "sub-42-3", titleHindi: "चार्ल्स मेटकॉफ की भूमिका एवं संधियों की प्रमुख शर्तें व खिराज", titleEnglish: "Charles Metcalfe & Treaty Terms" },
      { id: "sub-42-4", titleHindi: "संधियों के सामाजिक, आर्थिक व प्रशासनिक प्रभाव", titleEnglish: "Socio-Economic Impacts on Princely States" },
    ],
  },
  {
    id: 43,
    slug: "administrative-system-medieval-rajasthan",
    name: "Administrative System of Medieval Rajasthan",
    nameHindi: "मध्यकालीन राजस्थान की प्रशासनिक व्यवस्था",
    subjectSlug: "rajasthan-ancient-medieval-history",
    subjectHindi: "राजस्थान प्राचीन एवं मध्यकालीन इतिहास",
    examScope: "both",
    isCommon: true,
    commonKey: "raj-hist-admin",
    subTopics: [
      { id: "sub-43-1", titleHindi: "राजा की स्थिति, मंत्रिपरिषद एवं प्रमुख अधिकारी (प्रधान, दीवान, बख्शी)", titleEnglish: "Monarchy & Court Officials (Pradhan, Bakshi)" },
      { id: "sub-43-2", titleHindi: "सामंती व्यवस्था (जागीरदारी प्रथा, पट्टा रेख, भरतू रेख, हुक्मनामा)", titleEnglish: "Feudal System & Jagirdari Tenures" },
      { id: "sub-43-3", titleHindi: "भू-राजस्व व्यवस्था (लाटा, कुंता, बिघोड़ी, चौगुनी लगान)", titleEnglish: "Land Revenue & Assessment (Lata, Kunta)" },
      { id: "sub-43-4", titleHindi: "न्याय एवं सैन्य प्रशासन, स्थानीय ग्रामीण स्वशासन", titleEnglish: "Judicial, Military & Village Administration" },
    ],
  },

  // ─── D. आधुनिक राजस्थान एवं स्वतंत्रता आंदोलन (44 - 52) ───
  {
    id: 44,
    slug: "revolt-of-1857-in-rajasthan",
    name: "Revolt of 1857 in Rajasthan",
    nameHindi: "राजस्थान में 1857 का विद्रोह",
    subjectSlug: "modern-rajasthan-freedom-movement",
    subjectHindi: "आधुनिक राजस्थान एवं स्वतंत्रता आंदोलन",
    examScope: "both",
    isCommon: true,
    commonKey: "raj-hist-1857",
    subTopics: [
      { id: "sub-44-1", titleHindi: "विद्रोह के कारण, ए.जी.जी. (पैट्रिक लॉरेंस) व 6 सैनिक छावनियाँ", titleEnglish: "Causes, AGG & 6 Military Cantonments" },
      { id: "sub-44-2", titleHindi: "नसीराबाद एवं नीमच छावनी में विद्रोह (डूंगला कांड)", titleEnglish: "Nasirabad & Neemuch Outbreaks" },
      { id: "sub-44-3", titleHindi: "एरिनपुरा छावनी एवं आउवा का विद्रोह (कुशाल सिंह, बिथोड़ा व चेलावास युद्ध)", titleEnglish: "Auwa Uprising & Thakur Kushal Singh" },
      { id: "sub-44-4", titleHindi: "कोटा का व्यापक जनविद्रोह (जयदयाल, मेहराब खान, मेजर बर्टन की हत्या)", titleEnglish: "Kota Rebellion & Public Resistance" },
      { id: "sub-44-5", titleHindi: "तांतिया टोपे का राजस्थान आगमन, अमरचंद बांठिया व परिणाम", titleEnglish: "Tatya Tope & Amar Chand Banthia" },
    ],
  },
  {
    id: 45,
    slug: "peasant-and-tribal-movements-in-rajasthan",
    name: "Peasant and Tribal Movements in Rajasthan",
    nameHindi: "राजस्थान के किसान एवं जनजातीय आंदोलन",
    subjectSlug: "modern-rajasthan-freedom-movement",
    subjectHindi: "आधुनिक राजस्थान एवं स्वतंत्रता आंदोलन",
    examScope: "both",
    isCommon: true,
    commonKey: "raj-hist-peasant",
    subTopics: [
      { id: "sub-45-1", titleHindi: "बिजौलिया किसान आंदोलन (साधु सीताराम दास, विजय सिंह पथिक, माणिक्यलाल वर्मा)", titleEnglish: "Bijolia Peasant Movement (3 Phases)" },
      { id: "sub-45-2", titleHindi: "बेंगू, बूंदी (बरड़), अलवर एवं मेव किसान आंदोलन", titleEnglish: "Bengu, Bundi, Alwar & Meo Movements" },
      { id: "sub-45-3", titleHindi: "शेखावाटी किसान आंदोलन एवं कटराथल महिला सम्मेलन (1934)", titleEnglish: "Shekhawati & Katrathal Conference" },
      { id: "sub-45-4", titleHindi: "भगत आंदोलन एवं गोविंद गिरी (मानगढ़ धाम नरसंहार 1913)", titleEnglish: "Bhagat Movement & Govind Giri (Mangarh)" },
      { id: "sub-45-5", titleHindi: "एकी आंदोलन (मोतीलाल तेजावत, नीमड़ा हत्याकांड, मातृकुंडिया)", titleEnglish: "Eki Movement & Motilal Tejawat" },
      { id: "sub-45-6", titleHindi: "मीणा क्षेत्रीय सभा एवं जरायम पेशा कानून उन्मूलन", titleEnglish: "Meena Agitation & Jarayam Pesha Repeal" },
    ],
  },
  {
    id: 46,
    slug: "prajamandal-movements-in-rajasthan",
    name: "Prajamandal Movements in Rajasthan",
    nameHindi: "राजस्थान के प्रजामंडल आंदोलन",
    subjectSlug: "modern-rajasthan-freedom-movement",
    subjectHindi: "आधुनिक राजस्थान एवं स्वतंत्रता आंदोलन",
    examScope: "both",
    isCommon: true,
    commonKey: "raj-hist-prajamandal",
    subTopics: [
      { id: "sub-46-1", titleHindi: "जयपुर प्रजामंडल (कर्पूरचंद पाटनी, जमनालाल बजाज, हीरालाल शास्त्री)", titleEnglish: "Jaipur Prajamandal & Gentlemen's Agreement" },
      { id: "sub-46-2", titleHindi: "मेवाड़ प्रजामंडल (माणिक्यलाल वर्मा, बलवंत सिंह मेहता, प्रथम अधिवेशन)", titleEnglish: "Mewar Prajamandal" },
      { id: "sub-46-3", titleHindi: "मारवाड़ लोक परिषद (जयनारायण व्यास, छगनराज चौपासनी)", titleEnglish: "Marwar Lok Parishad" },
      { id: "sub-46-4", titleHindi: "बीकानेर, सिरोही, हाड़ौती, झालावाड़, डूंगरपुर प्रजामंडल", titleEnglish: "Bikaner, Sirohi & Hadoti Prajamandals" },
      { id: "sub-46-5", titleHindi: "प्रजामंडलों की स्थापना वर्ष, प्रमुख नेता एवं उत्तरदायी शासन मांग", titleEnglish: "Chronology & Responsible Government Demands" },
    ],
  },
  {
    id: 47,
    slug: "freedom-struggle-organizations-institutions",
    name: "Freedom Struggle Organizations and Institutions in Rajasthan",
    nameHindi: "राजस्थान में स्वतंत्रता आंदोलन के संगठन एवं संस्थाएँ",
    subjectSlug: "modern-rajasthan-freedom-movement",
    subjectHindi: "आधुनिक राजस्थान एवं स्वतंत्रता आंदोलन",
    examScope: "both",
    isCommon: true,
    commonKey: "raj-hist-orgs",
    subTopics: [
      { id: "sub-47-1", titleHindi: "वीर भारत सभा (केसरी सिंह बारहठ - 1910)", titleEnglish: "Veer Bharat Sabha" },
      { id: "sub-47-2", titleHindi: "राजस्थान सेवा संघ (वर्धा 1919, अजमेर स्थानांतरण)", titleEnglish: "Rajasthan Seva Sangh" },
      { id: "sub-47-3", titleHindi: "मारवाड़ सेवा संघ, सर्वहितकारिणी सभा (बीकानेर)", titleEnglish: "Marwar Seva Sangh & Sarvahitkarini Sabha" },
      { id: "sub-47-4", titleHindi: "राजपूताना मध्य भारत सभा एवं अखिल भारतीय देशी राज्य लोक परिषद", titleEnglish: "Rajputana Madhya Bharat Sabha & AISPC" },
    ],
  },
  {
    id: 48,
    slug: "social-and-political-awakening-in-rajasthan",
    name: "Social and Political Awakening in Rajasthan",
    nameHindi: "राजस्थान में सामाजिक एवं राजनीतिक जागरण",
    subjectSlug: "modern-rajasthan-freedom-movement",
    subjectHindi: "आधुनिक राजस्थान एवं स्वतंत्रता आंदोलन",
    examScope: "both",
    isCommon: true,
    commonKey: "raj-hist-awakening",
    subTopics: [
      { id: "sub-48-1", titleHindi: "स्वामी दयानंद सरस्वती का राजस्थान आगमन एवं आर्य समाज का प्रभाव", titleEnglish: "Swami Dayanand Saraswati & Arya Samaj" },
      { id: "sub-48-2", titleHindi: "परोपकारिणी सभा (उदयपुर) एवं सत्यार्थ प्रकाश रचना", titleEnglish: "Paropkarini Sabha & Satyarth Prakash" },
      { id: "sub-48-3", titleHindi: "शिक्षा प्रसार, महिला जागरण एवं कुप्रथा विरोधी चेतना", titleEnglish: "Spread of Education & Women Awakening" },
    ],
  },
  {
    id: 49,
    slug: "integration-of-rajasthan",
    name: "Integration of Rajasthan",
    nameHindi: "राजस्थान का एकीकरण",
    subjectSlug: "modern-rajasthan-freedom-movement",
    subjectHindi: "आधुनिक राजस्थान एवं स्वतंत्रता आंदोलन",
    examScope: "both",
    isCommon: true,
    commonKey: "raj-hist-integration",
    subTopics: [
      { id: "sub-49-1", titleHindi: "प्रथम चरण: मत्स्य संघ (18 मार्च 1948 - अलवर, भरतपुर, धौलपुर, करौली)", titleEnglish: "Stage 1: Matsya Sangh" },
      { id: "sub-49-2", titleHindi: "द्वितीय व तृतीय चरण: पूर्व राजस्थान संघ एवं संयुक्त राजस्थान संघ", titleEnglish: "Stages 2 & 3: Former & United Rajasthan" },
      { id: "sub-49-3", titleHindi: "चतुर्थ चरण: वृहत् राजस्थान (30 मार्च 1949 - राजस्थान दिवस)", titleEnglish: "Stage 4: Greater Rajasthan (30 March 1949)" },
      { id: "sub-49-4", titleHindi: "पंचम व षष्ठ चरण: संयुक्त वृहत् राजस्थान एवं सिरोही विलय विवाद", titleEnglish: "Stages 5 & 6: Sirohi Merger Issue" },
      { id: "sub-49-5", titleHindi: "सप्तम चरण: पुनर्गठित राजस्थान (1 नवंबर 1956 - अजमेर-मेरवाड़ा, आबू-देलवाड़ा)", titleEnglish: "Stage 7: Final Reorganization (1 Nov 1956)" },
      { id: "sub-49-6", titleHindi: "रियासती विभाग, सरदार पटेल, वी.पी. मेनन एवं विभिन्न समितियां", titleEnglish: "States Department, Patel & Key Committees" },
    ],
  },
  {
    id: 50,
    slug: "prominent-personalities-of-rajasthan",
    name: "Prominent Personalities of Rajasthan",
    nameHindi: "राजस्थान के प्रमुख व्यक्तित्व",
    subjectSlug: "modern-rajasthan-freedom-movement",
    subjectHindi: "आधुनिक राजस्थान एवं स्वतंत्रता आंदोलन",
    examScope: "both",
    isCommon: true,
    commonKey: "raj-hist-personalities",
    subTopics: [
      { id: "sub-50-1", titleHindi: "बारहठ परिवार: केसरी सिंह, जोरावर सिंह, प्रताप सिंह बारहठ", titleEnglish: "Barhath Family Freedom Fighters" },
      { id: "sub-50-2", titleHindi: "अर्जुनलाल सेठी, विजय सिंह पथिक, सागरमल गोपा (जैसलमेर का गुंडाराज)", titleEnglish: "Arjun Lal Sethi, Pathik & Sagarmal Gopa" },
      { id: "sub-50-3", titleHindi: "जमनालाल बजाज (गांधीजी के 5वें पुत्र) एवं हरिभाऊ उपाध्याय", titleEnglish: "Jamnalal Bajaj & Haribhau Upadhyaya" },
      { id: "sub-50-4", titleHindi: "गोकुलभाई भट्ट (राजस्थान के गांधी) एवं भोगीलाल पांड्या (वागड़ के गांधी)", titleEnglish: "Gokulbhai Bhatt & Bhogilal Pandya" },
    ],
  },
  {
    id: 51,
    slug: "prominent-women-personalities-of-rajasthan",
    name: "Prominent Women Personalities of Rajasthan",
    nameHindi: "राजस्थान की महिला व्यक्तित्व",
    subjectSlug: "modern-rajasthan-freedom-movement",
    subjectHindi: "आधुनिक राजस्थान एवं स्वतंत्रता आंदोलन",
    examScope: "both",
    isCommon: true,
    commonKey: "raj-hist-women",
    subTopics: [
      { id: "sub-51-1", titleHindi: "कालीबाई (रास्तापाल कांड 1947 - शिक्षा हेतु बलिदान)", titleEnglish: "Kalibai & Rastapal Incident" },
      { id: "sub-51-2", titleHindi: "किशोरी देवी (कटराथल महिला महासम्मेलन नेतृत्व)", titleEnglish: "Kishori Devi & Katrathal Conference" },
      { id: "sub-51-3", titleHindi: "रमा देवी, जानकी देवी बजाज, अंजना देवी चौधरी", titleEnglish: "Rama Devi, Janki Devi Bajaj, Anjana Devi" },
      { id: "sub-51-4", titleHindi: "रत्न शास्त्री (वनस्थली विद्यापीठ), नारायणी देवी वर्मा", titleEnglish: "Ratan Shastri & Banasthali Vidyapith" },
    ],
  },
  {
    id: 52,
    slug: "press-and-journalism-in-rajasthan",
    name: "Press and Journalism in Rajasthan",
    nameHindi: "राजस्थान में प्रेस एवं पत्रकारिता",
    subjectSlug: "modern-rajasthan-freedom-movement",
    subjectHindi: "आधुनिक राजस्थान एवं स्वतंत्रता आंदोलन",
    examScope: "both",
    isCommon: true,
    commonKey: "raj-hist-press",
    subTopics: [
      { id: "sub-52-1", titleHindi: "आरंभिक समाचार पत्र (मजहरुल सरूर, राजपूताना गजट, राजस्थान समाचार)", titleEnglish: "Early Newspapers of 19th Century" },
      { id: "sub-52-2", titleHindi: "विजय सिंह पथिक के पत्र (राजस्थान केसरी, नवीन राजस्थान, तरुण राजस्थान)", titleEnglish: "Vijay Singh Pathik's Publications" },
      { id: "sub-52-3", titleHindi: "त्यागभूमि (हरिभाऊ उपाध्याय), आगीबाण (जयनारायण व्यास)", titleEnglish: "Tyagbhoomi & Agibaan" },
      { id: "sub-52-4", titleHindi: "रियासती दमन के विरुद्ध समाचार पत्रों की भूमिका", titleEnglish: "Role of Nationalist Press Against Feudalism" },
    ],
  },

  // ─── E. राजस्थान राजव्यवस्था / प्रशासन (53 - 70) ───
  {
    id: 53,
    slug: "rajasthan-state-administration",
    name: "Rajasthan State Administration",
    nameHindi: "राजस्थान राज्य प्रशासन",
    subjectSlug: "rajasthan-polity-administration",
    subjectHindi: "राजस्थान राजव्यवस्था / प्रशासन",
    examScope: "both",
    isCommon: true,
    commonKey: "raj-pol-state-admin",
    subTopics: [
      { id: "sub-53-1", titleHindi: "राज्य सचिवालय का संगठन, कार्य एवं संरचना", titleEnglish: "State Secretariat Structure & Functions" },
      { id: "sub-53-2", titleHindi: "मुख्य सचिव: भूमिका, शक्तियाँ, पदसोपान एवं प्रथम मुख्य सचिव", titleEnglish: "Chief Secretary: Powers, Role & Precedence" },
      { id: "sub-53-3", titleHindi: "निदेशालय एवं सचिवालय संबंध (विभागाध्यक्ष की भूमिका)", titleEnglish: "Secretariat-Directorate Relations" },
    ],
  },
  {
    id: 54,
    slug: "governor-of-rajasthan",
    name: "Governor of Rajasthan",
    nameHindi: "राजस्थान के राज्यपाल",
    subjectSlug: "rajasthan-polity-administration",
    subjectHindi: "राजस्थान राजव्यवस्था / प्रशासन",
    examScope: "both",
    isCommon: true,
    commonKey: "raj-pol-governor",
    subTopics: [
      { id: "sub-54-1", titleHindi: "संवैधानिक प्रावधान (अनुच्छेद 153 से 162, नियुक्ति, योग्यताएं, शपथ)", titleEnglish: "Constitutional Provisions (Arts. 153-162)" },
      { id: "sub-54-2", titleHindi: "कार्यकारी, विधायी, वित्तीय, न्यायिक एवं स्वविवेकी शक्तियाँ", titleEnglish: "Executive, Legislative & Discretionary Powers" },
      { id: "sub-54-3", titleHindi: "राजस्थान के प्रमुख राज्यपाल एवं उनके कार्यकाल की विशिष्ट घटनाएं", titleEnglish: "Notable Governors & Historic Precedents" },
      { id: "sub-54-4", titleHindi: "राष्ट्रपति शासन (अनुच्छेद 356) - राजस्थान में 4 बार का विश्लेषण", titleEnglish: "President's Rule in Rajasthan (4 Instances)" },
    ],
  },
  {
    id: 55,
    slug: "chief-minister-of-rajasthan",
    name: "Chief Minister of Rajasthan",
    nameHindi: "राजस्थान के मुख्यमंत्री",
    subjectSlug: "rajasthan-polity-administration",
    subjectHindi: "राजस्थान राजव्यवस्था / प्रशासन",
    examScope: "both",
    isCommon: true,
    commonKey: "raj-pol-cm",
    subTopics: [
      { id: "sub-55-1", titleHindi: "संवैधानिक स्थिति (अनुच्छेद 163 व 164, नियुक्ति व पदमुक्ति)", titleEnglish: "Constitutional Position & Appointment" },
      { id: "sub-55-2", titleHindi: "मुख्यमंत्री के कार्य, शक्तियाँ एवं राज्यपाल से संबंध (अनुच्छेद 167)", titleEnglish: "Duties & Powers (Article 167)" },
      { id: "sub-55-3", titleHindi: "राजस्थान के मनोनीत व निर्वाचित मुख्यमंत्री (प्रथम मनोनीत, प्रथम निर्वाचित)", titleEnglish: "Nominated & Elected Chief Ministers" },
      { id: "sub-55-4", titleHindi: "सर्वाधिक कार्यकाल, अल्प कार्यकाल एवं महिला मुख्यमंत्री", titleEnglish: "Tenure Records & Notable Administrations" },
    ],
  },
  {
    id: 56,
    slug: "council-of-ministers-and-cabinet",
    name: "Council of Ministers and Cabinet of Rajasthan",
    nameHindi: "राजस्थान की मंत्रिपरिषद एवं मंत्रिमंडल",
    subjectSlug: "rajasthan-polity-administration",
    subjectHindi: "राजस्थान राजव्यवस्था / प्रशासन",
    examScope: "both",
    isCommon: true,
    commonKey: "raj-pol-cabinet",
    subTopics: [
      { id: "sub-56-1", titleHindi: "मंत्रिपरिषद की संरचना (कैबिनेट, राज्य मंत्री, उपमंत्री)", titleEnglish: "Composition: Cabinet, State & Deputy Ministers" },
      { id: "sub-56-2", titleHindi: "91वां संविधान संशोधन 2003 (अधिकतम 30 एवं न्यूनतम 12 मंत्री सीमा)", titleEnglish: "91st Amendment & Size Limits (15%)" },
      { id: "sub-56-3", titleHindi: "मंत्रिमंडल की कार्यप्रणाली, सामूहिक उत्तरदायित्व व कार्य आवंटन", titleEnglish: "Collective Responsibility & Rules of Business" },
    ],
  },
  {
    id: 57,
    slug: "rajasthan-state-legislature",
    name: "Rajasthan State Legislature",
    nameHindi: "राजस्थान राज्य विधानमंडल",
    subjectSlug: "rajasthan-polity-administration",
    subjectHindi: "राजस्थान राजव्यवस्था / प्रशासन",
    examScope: "both",
    isCommon: true,
    commonKey: "raj-pol-assembly",
    subTopics: [
      { id: "sub-57-1", titleHindi: "विधानसभा संरचना (200 सीटें, आरक्षित सीटें SC: 34, ST: 25)", titleEnglish: "Assembly Composition & Reserved Seats" },
      { id: "sub-57-2", titleHindi: "विधानसभा अध्यक्ष, उपाध्यक्ष एवं प्रोटेम स्पीकर की भूमिका", titleEnglish: "Speaker, Deputy Speaker & Protem Speaker" },
      { id: "sub-57-3", titleHindi: "विधायी प्रक्रिया, विधेयक पारित होना एवं बजट सत्र", titleEnglish: "Legislative Procedure & Budget Session" },
      { id: "sub-57-4", titleHindi: "विधानसभा की प्रमुख समितियाँ (लोक लेखा, प्राक्कलन समिति)", titleEnglish: "Assembly Committees (PAC, Estimates)" },
    ],
  },
  {
    id: 58,
    slug: "rajasthan-high-court-and-judiciary",
    name: "Rajasthan High Court and Judiciary",
    nameHindi: "राजस्थान उच्च न्यायालय एवं न्यायपालिका",
    subjectSlug: "rajasthan-polity-administration",
    subjectHindi: "राजस्थान राजव्यवस्था / प्रशासन",
    examScope: "both",
    isCommon: true,
    commonKey: "raj-pol-judiciary",
    subTopics: [
      { id: "sub-58-1", titleHindi: "उच्च न्यायालय स्थापना (29 अगस्त 1949), मुख्य पीठ जोधपुर व जयपुर खंडपीठ", titleEnglish: "Establishment, Principal Seat & Jaipur Bench" },
      { id: "sub-58-2", titleHindi: "न्यायाधीशों की नियुक्ति, योग्यताएं, शपथ, कार्यकाल व स्थानांतरण", titleEnglish: "Appointment & Tenure of Judges" },
      { id: "sub-58-3", titleHindi: "क्षेत्राधिकार एवं रिट जारी करने की शक्ति (अनुच्छेद 226)", titleEnglish: "Jurisdiction & Writ Powers (Art. 226)" },
      { id: "sub-58-4", titleHindi: "अधीनस्थ न्यायपालिका, लोक अदालतें एवं ग्राम न्यायालय", titleEnglish: "Subordinate Courts & Lok Adalats" },
    ],
  },
  {
    id: 59,
    slug: "district-administration-of-rajasthan",
    name: "District Administration of Rajasthan",
    nameHindi: "राजस्थान जिला प्रशासन",
    subjectSlug: "rajasthan-polity-administration",
    subjectHindi: "राजस्थान राजव्यवस्था / प्रशासन",
    examScope: "both",
    isCommon: true,
    commonKey: "raj-pol-dist-admin",
    subTopics: [
      { id: "sub-59-1", titleHindi: "जिला कलेक्टर: इतिहास, बहुआयामी भूमिका व कार्य (राजस्व, विकास, दंडाधिकारी)", titleEnglish: "District Collector: Powers & Duties" },
      { id: "sub-59-2", titleHindi: "उपखंड अधिकारी (SDM), तहसीलदार एवं पटवारी का दायित्व", titleEnglish: "SDM, Tehsildar & Patwari Roles" },
      { id: "sub-59-3", titleHindi: "जिला पुलिस प्रशासन (SP की भूमिका व कानून व्यवस्था)", titleEnglish: "District Police Hierarchy (SP & Law & Order)" },
      { id: "sub-59-4", titleHindi: "विभागीय समन्वय एवं जिला आपदा प्रबंधन प्राधिकरण", titleEnglish: "Disaster Management & Inter-Agency Coordination" },
    ],
  },
  {
    id: 60,
    slug: "panchayati-raj-in-rajasthan",
    name: "Panchayati Raj in Rajasthan",
    nameHindi: "राजस्थान पंचायती राज",
    subjectSlug: "rajasthan-polity-administration",
    subjectHindi: "राजस्थान राजव्यवस्था / प्रशासन",
    examScope: "both",
    isCommon: true,
    commonKey: "raj-pol-panchayat",
    subTopics: [
      { id: "sub-60-1", titleHindi: "ऐतिहासिक पृष्ठभूमि (2 अक्टूबर 1959 - नागौर के बगदरी में नेहरूजी द्वारा उद्घाटन)", titleEnglish: "Nagaur Launch (2 Oct 1959) by Nehru" },
      { id: "sub-60-2", titleHindi: "73वां संविधान संशोधन अधिनियम एवं 11वीं अनुसूची के 29 विषय", titleEnglish: "73rd Amendment & 29 Subjects" },
      { id: "sub-60-3", titleHindi: "राजस्थान पंचायती राज अधिनियम 1994 एवं त्रि-स्तरीय ढांचा (ग्राम, ब्लॉक, जिला)", titleEnglish: "Rajasthan Panchayati Raj Act 1994" },
      { id: "sub-60-4", titleHindi: "ग्राम सभा, ग्राम पंचायत, पंचायत समिति एवं जिला परिषद कार्य", titleEnglish: "Gram Sabha & Standing Committees" },
      { id: "sub-60-5", titleHindi: "महिला आरक्षण (50%), पेसा अधिनियम 1996 (PESA Act)", titleEnglish: "50% Women Reservation & PESA in TSP" },
    ],
  },
  {
    id: 61,
    slug: "rajasthan-public-service-commission-rpsc",
    name: "Rajasthan Public Service Commission RPSC",
    nameHindi: "राजस्थान लोक सेवा आयोग (RPSC)",
    subjectSlug: "rajasthan-polity-administration",
    subjectHindi: "राजस्थान राजव्यवस्था / प्रशासन",
    examScope: "both",
    isCommon: true,
    commonKey: "raj-pol-rpsc",
    subTopics: [
      { id: "sub-61-1", titleHindi: "संवैधानिक प्रावधान (अनुच्छेद 315 से 323, स्थापना 20 अगस्त 1949)", titleEnglish: "Constitutional Basis (Arts. 315-323) & Setup" },
      { id: "sub-61-2", titleHindi: "अध्यक्ष एवं सदस्यों की संरचना (1 अध्यक्ष + 7 सदस्य), योग्यता व कार्यकाल", titleEnglish: "Composition (1+7), Qualifications & Tenure" },
      { id: "sub-61-3", titleHindi: "पदमुक्ति प्रक्रिया (अनुच्छेद 317 - उच्चतम न्यायालय जांच)", titleEnglish: "Removal Procedure (Art. 317)" },
      { id: "sub-61-4", titleHindi: "RPSC के कार्य, सलाहकार भूमिका एवं वार्षिक प्रतिवेदन", titleEnglish: "Functions, Advisory Role & Annual Report" },
    ],
  },
  {
    id: 62,
    slug: "rajasthan-state-election-commission",
    name: "Rajasthan State Election Commission",
    nameHindi: "राजस्थान राज्य निर्वाचन आयोग",
    subjectSlug: "rajasthan-polity-administration",
    subjectHindi: "राजस्थान राजव्यवस्था / प्रशासन",
    examScope: "both",
    isCommon: true,
    commonKey: "raj-pol-sec",
    subTopics: [
      { id: "sub-62-1", titleHindi: "संवैधानिक आधार (अनुच्छेद 243-K एवं 243-ZA, स्थापना जुलाई 1994)", titleEnglish: "Constitutional Basis (Arts. 243K & 243ZA)" },
      { id: "sub-62-2", titleHindi: "राज्य निर्वाचन आयुक्त की नियुक्ति, सेवा शर्तें व पदमुक्ति", titleEnglish: "State Election Commissioner: Terms & Removal" },
      { id: "sub-62-3", titleHindi: "पंचायती राज एवं नगरीय निकायों के चुनाव संचालन अधिकार", titleEnglish: "Conduct of Local Body Elections" },
    ],
  },
  {
    id: 63,
    slug: "rajasthan-state-human-rights-commission",
    name: "Rajasthan State Human Rights Commission",
    nameHindi: "राजस्थान मानवाधिकार आयोग",
    subjectSlug: "rajasthan-polity-administration",
    subjectHindi: "राजस्थान राजव्यवस्था / प्रशासन",
    examScope: "both",
    isCommon: true,
    commonKey: "raj-pol-shrc",
    subTopics: [
      { id: "sub-63-1", titleHindi: "गठन (मानवाधिकार संरक्षण अधिनियम 1993, गठन 18 जनवरी 1999)", titleEnglish: "Establishment under PHRA 1993" },
      { id: "sub-63-2", titleHindi: "संरचना (1 अध्यक्ष + 2 सदस्य), चयन समिति (CM, गृहमंत्री, स्पीकर, विपक्ष नेता)", titleEnglish: "Composition (1+2) & Selection Panel" },
      { id: "sub-63-3", titleHindi: "कार्यकाल (3 वर्ष या 70 वर्ष), शक्तियाँ एवं सिविल कोर्ट अधिकार", titleEnglish: "Tenure (3 Yrs/70 Yrs) & Civil Court Powers" },
      { id: "sub-63-4", titleHindi: "आयोग की कार्यप्रणाली, सीमाएं एवं वार्षिक रिपोर्ट", titleEnglish: "Investigation Mechanism & Limitations" },
    ],
  },
  {
    id: 64,
    slug: "rajasthan-state-commission-for-women",
    name: "Rajasthan State Commission for Women",
    nameHindi: "राजस्थान महिला आयोग",
    subjectSlug: "rajasthan-polity-administration",
    subjectHindi: "राजस्थान राजव्यवस्था / प्रशासन",
    examScope: "both",
    isCommon: false,
    subTopics: [
      { id: "sub-64-1", titleHindi: "अधिनियम 1999, गठन (15 मई 1999) एवं संरचना (1 अध्यक्ष + 3 सदस्य)", titleEnglish: "Establishment (1999) & Structure (1+3)" },
      { id: "sub-64-2", titleHindi: "कार्यकाल (3 वर्ष) एवं महिला अधिकारों के संरक्षण कार्य", titleEnglish: "3-Year Tenure & Women Safeguards" },
      { id: "sub-64-3", titleHindi: "महिला उत्पीड़न निवारण, जांच शक्तियाँ एवं जनसुनवाई", titleEnglish: "Inquiry into Gender Injustice & Hearings" },
    ],
  },
  {
    id: 65,
    slug: "lokayukta-of-rajasthan",
    name: "Lokayukta of Rajasthan",
    nameHindi: "राजस्थान लोकायुक्त",
    subjectSlug: "rajasthan-polity-administration",
    subjectHindi: "राजस्थान राजव्यवस्था / प्रशासन",
    examScope: "both",
    isCommon: true,
    commonKey: "raj-pol-lokayukta",
    subTopics: [
      { id: "sub-65-1", titleHindi: "राजस्थान लोकायुक्त एवं उप-लोकायुक्त अधिनियम 1973 (स्थापना अगस्त 1973)", titleEnglish: "Lokayukta Act 1973 & Background" },
      { id: "sub-65-2", titleHindi: "नियुक्ति (राज्यपाल द्वारा CM, CJI, विपक्ष नेता परामर्श), योग्यता व कार्यकाल (5 वर्ष)", titleEnglish: "Appointment & 5-Year Tenure" },
      { id: "sub-65-3", titleHindi: "जांच का क्षेत्राधिकार (मंत्री, सचिव, जनसेवक) एवं छूट (मुख्यमंत्री, MLA, न्यायपालिका)", titleEnglish: "Jurisdiction & Exemptions (CM, MLAs)" },
      { id: "sub-65-4", titleHindi: "प्रथम लोकायुक्त (न्यायमूर्ति आई.डी. दुआ) एवं सिफारिशी स्वरूप", titleEnglish: "First Lokayukta (Justice ID Dua) & Powers" },
    ],
  },
  {
    id: 66,
    slug: "constitutional-commissions-and-institutions",
    name: "Constitutional Commissions and Institutions of Rajasthan",
    nameHindi: "राजस्थान के संवैधानिक आयोग एवं संस्थाएँ",
    subjectSlug: "rajasthan-polity-administration",
    subjectHindi: "राजस्थान राजव्यवस्था / प्रशासन",
    examScope: "both",
    isCommon: true,
    commonKey: "raj-pol-commissions",
    subTopics: [
      { id: "sub-66-1", titleHindi: "राज्य वित्त आयोग (अनुच्छेद 243-I एवं 243-Y - 6वें वित्त आयोग विश्लेषण)", titleEnglish: "State Finance Commission (6th SFC)" },
      { id: "sub-66-2", titleHindi: "राज्य सूचना आयोग (RTI Act 2005 - मुख्य सूचना आयुक्त व शक्तियाँ)", titleEnglish: "State Information Commission (RTI Act)" },
      { id: "sub-66-3", titleHindi: "राजस्थान लोक सेवा गारंटी अधिनियम 2011 एवं जवाबदेही कानून", titleEnglish: "Public Service Guarantee Act 2011" },
    ],
  },
  {
    id: 67,
    slug: "research-and-study-centers-of-rajasthan",
    name: "Research and Study Centers of Rajasthan",
    nameHindi: "राजस्थान के प्रमुख अनुसंधान एवं अध्ययन केंद्र",
    subjectSlug: "rajasthan-polity-administration",
    subjectHindi: "राजस्थान राजव्यवस्था / प्रशासन",
    examScope: "both",
    isCommon: true,
    commonKey: "raj-pol-research",
    subTopics: [
      { id: "sub-67-1", titleHindi: "काजरी (CAZRI) एवं आफरी (AFRI) - जोधपुर", titleEnglish: "CAZRI & AFRI (Jodhpur)" },
      { id: "sub-67-2", titleHindi: "राष्ट्रीय बीजीय मसाला अनुसंधान केंद्र (तबीजी, अजमेर) व ऊंट अनुसंधान (जोहड़बीड़)", titleEnglish: "NRCSS Ajmer & Camel Research Bikaner" },
      { id: "sub-67-3", titleHindi: "केंद्रीय भेड़ एवं ऊन अनुसंधान संस्थान (अविकानगर, टोंक)", titleEnglish: "CSWRI Avikanagar (Tonk)" },
      { id: "sub-67-4", titleHindi: "राजस्थान प्राच्य विद्या प्रतिष्ठान एवं भाषा शोध संस्थान", titleEnglish: "Rajasthan Oriental Research Institute" },
    ],
  },
  {
    id: 68,
    slug: "science-and-technology-in-rajasthan",
    name: "Science and Technology in Rajasthan",
    nameHindi: "राजस्थान विज्ञान एवं प्रौद्योगिकी",
    subjectSlug: "rajasthan-polity-administration",
    subjectHindi: "राजस्थान राजव्यवस्था / प्रशासन",
    examScope: "both",
    isCommon: false,
    subTopics: [
      { id: "sub-68-1", titleHindi: "विज्ञान एवं प्रौद्योगिकी विभाग (DST, राजस्थान)", titleEnglish: "Department of Science & Tech" },
      { id: "sub-68-2", titleHindi: "रिमोट सेंसिंग एप्लीकेशन सेंटर (SRSAC, जोधपुर)", titleEnglish: "State Remote Sensing Centre (Jodhpur)" },
      { id: "sub-68-3", titleHindi: "पोखरण परमाणु परीक्षण स्थल (1974 व 1998 इतिहास)", titleEnglish: "Pokhran Nuclear Test Range History" },
      { id: "sub-68-4", titleHindi: "उदयपुर सोलर ऑब्जर्वेटरी (USO) एवं माउंट आबू वेधशाला", titleEnglish: "Udaipur Solar Observatory (USO)" },
    ],
  },
  {
    id: 69,
    slug: "urban-local-self-government-municipalities",
    name: "Urban Local Self-Government and Municipalities",
    nameHindi: "राजस्थान नगरीय स्वशासन एवं नगरपालिका",
    subjectSlug: "rajasthan-polity-administration",
    subjectHindi: "राजस्थान राजव्यवस्था / प्रशासन",
    examScope: "both",
    isCommon: true,
    commonKey: "raj-pol-urban",
    subTopics: [
      { id: "sub-69-1", titleHindi: "74वां संविधान संशोधन अधिनियम एवं 12वीं अनुसूची के 18 विषय", titleEnglish: "74th Amendment & 18 Municipal Subjects" },
      { id: "sub-69-2", titleHindi: "राजस्थान नगरपालिका अधिनियम 2009 की प्रमुख धाराएं", titleEnglish: "Rajasthan Municipalities Act 2009" },
      { id: "sub-69-3", titleHindi: "त्रि-स्तरीय नगरीय ढांचा (नगर निगम, नगर परिषद, नगर पालिका बोर्ड)", titleEnglish: "Municipal Corporations, Councils & Boards" },
      { id: "sub-69-4", titleHindi: "महापौर (Mayor), सभापति, आयुक्त एवं वार्ड समितियों की भूमिका", titleEnglish: "Mayors, Commissioners & Ward Panels" },
    ],
  },
  {
    id: 70,
    slug: "budget-and-economic-review-of-rajasthan",
    name: "Budget and Economic Review of Rajasthan",
    nameHindi: "राजस्थान का बजट एवं आर्थिक समीक्षा",
    subjectSlug: "rajasthan-polity-administration",
    subjectHindi: "राजस्थान राजव्यवस्था / प्रशासन",
    examScope: "both",
    isCommon: true,
    commonKey: "raj-pol-budget",
    subTopics: [
      { id: "sub-70-1", titleHindi: "सकल राज्य घरेलू उत्पाद (GSDP) - स्थिर एवं प्रचलित मूल्य", titleEnglish: "GSDP at Constant & Current Prices" },
      { id: "sub-70-2", titleHindi: "क्षेत्रवार योगदान (कृषि, उद्योग, सेवा क्षेत्र का प्रतिशत)", titleEnglish: "Sectoral Share: Agri, Industry, Services" },
      { id: "sub-70-3", titleHindi: "प्रति व्यक्ति आय (Per Capita Income) एवं राजकोषीय घाटा", titleEnglish: "Per Capita Income & Fiscal Deficit" },
      { id: "sub-70-4", titleHindi: "राज्य की प्रमुख फ्लैगशिप योजनाएं एवं बजट घोषणाएं", titleEnglish: "State Flagship Schemes & Budget Highlights" },
    ],
  },
];

// Helper functions for static access
export function getStaticSubjects(): StaticSubject[] {
  return CANONICAL_SUBJECTS;
}

export function getStaticSubjectBySlug(slug: string): StaticSubject | undefined {
  return CANONICAL_SUBJECTS.find((s) => s.slug === slug);
}

export function getStaticTopics(): StaticTopic[] {
  return CANONICAL_TOPICS;
}

export function getStaticTopicById(id: number): StaticTopic | undefined {
  return CANONICAL_TOPICS.find((t) => t.id === id);
}

export function getStaticTopicBySlug(slug: string): StaticTopic | undefined {
  return CANONICAL_TOPICS.find((t) => t.slug === slug);
}

export function getStaticTopicsBySubject(subjectSlug: string): StaticTopic[] {
  return CANONICAL_TOPICS.filter((t) => t.subjectSlug === subjectSlug);
}
