/**
 * Authoritative Syllabus Data for:
 * 1. RPSC Senior Teacher (2nd Grade) Paper-I (GK & Educational Psychology)
 * 2. RSMSSB CET (Graduation & 12th Level)
 * 3. Merged / Common Topics Overlap Analysis & 75 Master Topics Mapping
 */

export interface SyllabusTopicItem {
  id: string;
  titleHindi: string;
  titleEnglish: string;
  section: string; // e.g. "खंड- I: राजस्थान का भौगोलिक, ऐतिहासिक, सांस्कृतिक और सामान्य ज्ञान" or "दैनिक विज्ञान"
  subSection?: string; // e.g. "1. भूगोल (Geography)"
  isCommon: boolean; // Present in both Senior Teacher & CET
  commonKey?: string; // Key linking Senior Teacher topic with CET topic
  commonNotes?: string; // Explanation of overlap
  canonicalTopicId?: number; // 1-75 ID if mapped to Master Syllabus
  canonicalTopicName?: string; // Canonical 75 Topic Name
  examScope: "SENIOR_TEACHER" | "CET" | "BOTH";
}

export interface SyllabusSectionGroup {
  id: string;
  titleHindi: string;
  titleEnglish: string;
  topics: SyllabusTopicItem[];
}

// ─────────────────────────────────────────────────────────────────────────────
// 1. RPSC Senior Teacher (2nd Grade) Paper-1 Syllabus
// ─────────────────────────────────────────────────────────────────────────────
export const SENIOR_TEACHER_SYLLABUS: SyllabusTopicItem[] = [
  // खंड- I: 1. भूगोल (Geography)
  {
    id: "st-geo-1",
    titleHindi: "भौतिक विशेषताएं (Physical Features)",
    titleEnglish: "Physical Features of Rajasthan",
    section: "खंड- I: राजस्थान सामान्य ज्ञान, इतिहास एवं संस्कृति",
    subSection: "1. भूगोल (Geography)",
    isCommon: true,
    commonKey: "raj-geo-physical",
    commonNotes: "CET में भी 'राजस्थान के भौतिक स्वरूप' के रूप में पूर्णतः शामिल है।",
    canonicalTopicId: 2,
    canonicalTopicName: "राजस्थान का भौतिक स्वरूप एवं भूगोल",
    examScope: "BOTH",
  },
  {
    id: "st-geo-2",
    titleHindi: "जलवायु (Climate)",
    titleEnglish: "Climate of Rajasthan",
    section: "खंड- I: राजस्थान सामान्य ज्ञान, इतिहास एवं संस्कृति",
    subSection: "1. भूगोल (Geography)",
    isCommon: true,
    commonKey: "raj-geo-climate",
    commonNotes: "CET में 'जलवायु दशाएं एवं मानसून तंत्र' के रूप में कॉमन है।",
    canonicalTopicId: 3,
    canonicalTopicName: "राजस्थान की जलवायु",
    examScope: "BOTH",
  },
  {
    id: "st-geo-3",
    titleHindi: "अपवाह तंत्र / नदियाँ (Drainage System & Rivers)",
    titleEnglish: "Drainage System and Rivers",
    section: "खंड- I: राजस्थान सामान्य ज्ञान, इतिहास एवं संस्कृति",
    subSection: "1. भूगोल (Geography)",
    isCommon: true,
    commonKey: "raj-geo-rivers",
    commonNotes: "CET में 'अपवाह तंत्र, नदियां, बांध एवं झीलें' कॉमन टॉपिक है।",
    canonicalTopicId: 7,
    canonicalTopicName: "राजस्थान की नदियाँ एवं जल संसाधन",
    examScope: "BOTH",
  },
  {
    id: "st-geo-4",
    titleHindi: "प्राकृतिक वनस्पति (Natural Vegetation)",
    titleEnglish: "Natural Vegetation & Forest Wealth",
    section: "खंड- I: राजस्थान सामान्य ज्ञान, इतिहास एवं संस्कृति",
    subSection: "1. भूगोल (Geography)",
    isCommon: true,
    commonKey: "raj-geo-vegetation",
    commonNotes: "CET में 'वन संपदा एवं वनस्पति' के रूप में कॉमन है।",
    canonicalTopicId: 10,
    canonicalTopicName: "राजस्थान के वन एवं वन्यजीव",
    examScope: "BOTH",
  },
  {
    id: "st-geo-5",
    titleHindi: "कृषि (Agriculture)",
    titleEnglish: "Agriculture & Cropping Pattern",
    section: "खंड- I: राजस्थान सामान्य ज्ञान, इतिहास एवं संस्कृति",
    subSection: "1. भूगोल (Geography)",
    isCommon: true,
    commonKey: "raj-geo-agri",
    commonNotes: "CET में 'प्रमुख फसलें एवं कृषि आधारित उद्योग' कॉमन है।",
    canonicalTopicId: 13,
    canonicalTopicName: "राजस्थान की कृषि",
    examScope: "BOTH",
  },
  {
    id: "st-geo-6",
    titleHindi: "पशुधन एवं डेयरी विकास (Livestock & Dairy Development)",
    titleEnglish: "Livestock & Dairy Development",
    section: "खंड- I: राजस्थान सामान्य ज्ञान, इतिहास एवं संस्कृति",
    subSection: "1. भूगोल (Geography)",
    isCommon: true,
    commonKey: "raj-geo-livestock",
    commonNotes: "CET में 'पशु संपदा एवं नस्लें' समान टॉपिक है।",
    canonicalTopicId: 14,
    canonicalTopicName: "राजस्थान का पशुपालन",
    examScope: "BOTH",
  },
  {
    id: "st-geo-7",
    titleHindi: "जनसांख्यिकीय विशेषताएं (Demographic Characteristics)",
    titleEnglish: "Population & Demographics",
    section: "खंड- I: राजस्थान सामान्य ज्ञान, इतिहास एवं संस्कृति",
    subSection: "1. भूगोल (Geography)",
    isCommon: true,
    commonKey: "raj-geo-demography",
    commonNotes: "CET में 'जनसंख्या वृद्धि, घनत्व, साक्षरता, लिंगानुपात' कॉमन है।",
    canonicalTopicId: 5,
    canonicalTopicName: "राजस्थान की जनसंख्या एवं जनगणना",
    examScope: "BOTH",
  },
  {
    id: "st-geo-8",
    titleHindi: "जनजातियाँ (Tribes of Rajasthan)",
    titleEnglish: "Tribes of Rajasthan",
    section: "खंड- I: राजस्थान सामान्य ज्ञान, इतिहास एवं संस्कृति",
    subSection: "1. भूगोल (Geography)",
    isCommon: true,
    commonKey: "raj-geo-tribes",
    commonNotes: "CET में 'राजस्थान की प्रमुख जनजातियां' समान टॉपिक है।",
    canonicalTopicId: 5,
    canonicalTopicName: "राजस्थान की जनसंख्या एवं जनगणना",
    examScope: "BOTH",
  },
  {
    id: "st-geo-9",
    titleHindi: "उद्योग (Industries of Rajasthan)",
    titleEnglish: "Major Industries of Rajasthan",
    section: "खंड- I: राजस्थान सामान्य ज्ञान, इतिहास एवं संस्कृति",
    subSection: "1. भूगोल (Geography)",
    isCommon: true,
    commonKey: "raj-geo-industries",
    commonNotes: "CET में 'प्रमुख उद्योग एवं औद्योगिक विकास' कॉमन है।",
    canonicalTopicId: 17,
    canonicalTopicName: "राजस्थान के प्रमुख उद्योग",
    examScope: "BOTH",
  },
  {
    id: "st-geo-10",
    titleHindi: "पर्यटन और प्रमुख पर्यटन केंद्र (Tourism & Major Centres)",
    titleEnglish: "Tourism & Major Tourist Centres",
    section: "खंड- I: राजस्थान सामान्य ज्ञान, इतिहास एवं संस्कृति",
    subSection: "1. भूगोल (Geography)",
    isCommon: true,
    commonKey: "raj-geo-tourism",
    commonNotes: "CET में 'पर्यटन स्थल एवं सर्किट' समान टॉपिक है।",
    canonicalTopicId: 19,
    canonicalTopicName: "राजस्थान का पर्यटन",
    examScope: "BOTH",
  },

  // खंड- I: 2. प्राचीन संस्कृति और सभ्यता
  {
    id: "st-anc-1",
    titleHindi: "प्राचीन स्थल और उनका महत्व (कालीबंगा, आहड़, गणेश्वर, बैराठ आदि)",
    titleEnglish: "Ancient Civilizations: Kalibanga, Ahar, Ganeshwar, Bairath",
    section: "खंड- I: राजस्थान सामान्य ज्ञान, इतिहास एवं संस्कृति",
    subSection: "2. प्राचीन संस्कृति और सभ्यता",
    isCommon: true,
    commonKey: "raj-hist-ancient-sites",
    commonNotes: "CET में हूबहू कालीबंगा, आहड़, गणेश्वर, बालाथल और बैराठ का उल्लेख है।",
    canonicalTopicId: 37,
    canonicalTopicName: "राजस्थान की प्राचीन सभ्यताएँ एवं पुरातात्विक स्थल",
    examScope: "BOTH",
  },

  // खंड- I: 3. राजस्थान का इतिहास (18वीं शताब्दी तक)
  {
    id: "st-hist-1",
    titleHindi: "राजस्थान के प्रमुख राजपूत राजवंश",
    titleEnglish: "Major Rajput Dynasties of Rajasthan",
    section: "खंड- I: राजस्थान सामान्य ज्ञान, इतिहास एवं संस्कृति",
    subSection: "3. राजस्थान का इतिहास (18वीं शताब्दी तक)",
    isCommon: true,
    commonKey: "raj-hist-dynasties",
    commonNotes: "CET में 'प्रमुख राजवंश एवं उनकी प्रशासनिक व राजस्व व्यवस्था' शामिल है।",
    canonicalTopicId: 40,
    canonicalTopicName: "राजस्थान का राजपूत काल",
    examScope: "BOTH",
  },
  {
    id: "st-hist-2",
    titleHindi: "दिल्ली सल्तनत के साथ संबंध (मेवाड़, रणथंभौर और जालोर)",
    titleEnglish: "Relations with Delhi Sultanate: Mewar, Ranthambore, Jalore",
    section: "खंड- I: राजस्थान सामान्य ज्ञान, इतिहास एवं संस्कृति",
    subSection: "3. राजस्थान का इतिहास (18वीं शताब्दी तक)",
    isCommon: true,
    commonKey: "raj-hist-sultanate-relations",
    commonNotes: "CET में सल्तनतकालीन ऐतिहासिक लड़ाइयां व संधियां पूछी जाती हैं।",
    canonicalTopicId: 41,
    canonicalTopicName: "मेवाड़ का गुहिल/गुहिलोत वंश",
    examScope: "BOTH",
  },
  {
    id: "st-hist-3",
    titleHindi: "राजस्थान और मुगल (मेवाड़, मारवाड़, आमेर और बीकानेर: सांगा, प्रताप, मानसिंह, चंद्रसेन, रायसिंह, राजसिंह)",
    titleEnglish: "Rajasthan & Mughals (Sanga, Pratap, Mansingh, Chandrasen, Raisingh, Rajsingh)",
    section: "खंड- I: राजस्थान सामान्य ज्ञान, इतिहास एवं संस्कृति",
    subSection: "3. राजस्थान का इतिहास (18वीं शताब्दी तक)",
    isCommon: true,
    commonKey: "raj-hist-mughal-relations",
    commonNotes: "CET में मुगल-राजपूत प्रतिरोध व संधियों के प्रश्न पूछे जाते हैं।",
    canonicalTopicId: 42,
    canonicalTopicName: "आमेर का कछवाहा वंश",
    examScope: "BOTH",
  },

  // खंड- I: 4. स्वतंत्रता संग्राम का इतिहास
  {
    id: "st-free-1",
    titleHindi: "1857 की क्रांति (Revolt of 1857 in Rajasthan)",
    titleEnglish: "1857 Revolt in Rajasthan",
    section: "खंड- I: राजस्थान सामान्य ज्ञान, इतिहास एवं संस्कृति",
    subSection: "4. स्वतंत्रता संग्राम का इतिहास",
    isCommon: true,
    commonKey: "raj-hist-1857",
    commonNotes: "CET में 1857 की क्रांति (एरिनपुरा, नसीराबाद, आउवा आदि) महत्वपूर्ण है।",
    canonicalTopicId: 49,
    canonicalTopicName: "राजस्थान में 1857 का विद्रोह",
    examScope: "BOTH",
  },
  {
    id: "st-free-2",
    titleHindi: "राजनीतिक जनजागृति (Political Awakening in Rajasthan)",
    titleEnglish: "Political Awakening in Rajasthan",
    section: "खंड- I: राजस्थान सामान्य ज्ञान, इतिहास एवं संस्कृति",
    subSection: "4. स्वतंत्रता संग्राम का इतिहास",
    isCommon: true,
    commonKey: "raj-hist-awakening",
    commonNotes: "CET में सामाजिक व राजनीतिक जनजागरण समान भाग है।",
    canonicalTopicId: 53,
    canonicalTopicName: "राजस्थान में सामाजिक एवं राजनीतिक जागरण",
    examScope: "BOTH",
  },
  {
    id: "st-free-3",
    titleHindi: "प्रजामंडल आंदोलन (Prajamandal Movements)",
    titleEnglish: "Prajamandal Movements",
    section: "खंड- I: राजस्थान सामान्य ज्ञान, इतिहास एवं संस्कृति",
    subSection: "4. स्वतंत्रता संग्राम का इतिहास",
    isCommon: true,
    commonKey: "raj-hist-prajamandal",
    commonNotes: "CET में प्रजामंडल आंदोलन पूर्णतः शामिल है।",
    canonicalTopicId: 51,
    canonicalTopicName: "राजस्थान के प्रजामंडल आंदोलन",
    examScope: "BOTH",
  },
  {
    id: "st-free-4",
    titleHindi: "किसान और आदिवासी आंदोलन (Peasant & Tribal Movements)",
    titleEnglish: "Peasant and Tribal Movements (Bijolia, Bengu, etc.)",
    section: "खंड- I: राजस्थान सामान्य ज्ञान, इतिहास एवं संस्कृति",
    subSection: "4. स्वतंत्रता संग्राम का इतिहास",
    isCommon: true,
    commonKey: "raj-hist-peasant-tribal",
    commonNotes: "CET में बिजोलिया, बेंगू, गोविंद गिरि व मोतीलाल तेजावत आंदोलन शामिल हैं।",
    canonicalTopicId: 50,
    canonicalTopicName: "राजस्थान के किसान एवं जनजातीय आंदोलन",
    examScope: "BOTH",
  },

  // खंड- I: 5. राजस्थान का एकीकरण
  {
    id: "st-integ-1",
    titleHindi: "राजस्थान का एकीकरण (Integration of Rajasthan - 7 Stages)",
    titleEnglish: "Integration of Rajasthan (7 Stages)",
    section: "खंड- I: राजस्थान सामान्य ज्ञान, इतिहास एवं संस्कृति",
    subSection: "5. राजस्थान का एकीकरण",
    isCommon: true,
    commonKey: "raj-hist-integration",
    commonNotes: "CET में राजस्थान के एकीकरण के सातों चरण शत-प्रतिशत कॉमन हैं।",
    canonicalTopicId: 54,
    canonicalTopicName: "राजस्थान का एकीकरण",
    examScope: "BOTH",
  },

  // खंड- I: 6. समाज और धर्म
  {
    id: "st-soc-1",
    titleHindi: "लोक देवता और देवियां (Folk Deities & Goddesses)",
    titleEnglish: "Folk Deities and Goddesses",
    section: "खंड- I: राजस्थान सामान्य ज्ञान, इतिहास एवं संस्कृति",
    subSection: "6. समाज और धर्म",
    isCommon: true,
    commonKey: "raj-cult-deities",
    commonNotes: "CET में पाबूजी, तेजाजी, रामदेवजी आदि लोकदेवता समान रूप से हैं।",
    canonicalTopicId: 28,
    canonicalTopicName: "राजस्थान के लोक देवता एवं लोक देवियाँ",
    examScope: "BOTH",
  },
  {
    id: "st-soc-2",
    titleHindi: "राजस्थान के संत एवं संप्रदाय (Saints & Sects)",
    titleEnglish: "Saints and Religious Sects",
    section: "खंड- I: राजस्थान सामान्य ज्ञान, इतिहास एवं संस्कृति",
    subSection: "6. समाज और धर्म",
    isCommon: true,
    commonKey: "raj-cult-saints",
    commonNotes: "CET में दादू दयाल, जाम्भोजी, जसनाथी, चरणदासी आदि संप्रदाय शामिल हैं।",
    canonicalTopicId: 29,
    canonicalTopicName: "राजस्थान के संत, संप्रदाय एवं धार्मिक परंपराएँ",
    examScope: "BOTH",
  },
  {
    id: "st-soc-3",
    titleHindi: "स्थापत्य कला: मंदिर, किले, महल और स्मारक (Architecture: Temples, Forts, Palaces)",
    titleEnglish: "Architecture: Temples, Forts, Palaces & Monuments",
    section: "खंड- I: राजस्थान सामान्य ज्ञान, इतिहास एवं संस्कृति",
    subSection: "6. समाज और धर्म",
    isCommon: true,
    commonKey: "raj-cult-architecture",
    commonNotes: "CET में किले, छतरियां, महल एवं स्मारक प्रमुखता से शामिल हैं।",
    canonicalTopicId: 25,
    canonicalTopicName: "राजस्थान की स्थापत्य कला एवं वास्तुकला",
    examScope: "BOTH",
  },
  {
    id: "st-soc-4",
    titleHindi: "चित्रकला: विभिन्न स्कूल / शैलियाँ (Painting Schools & Styles)",
    titleEnglish: "Painting Schools & Styles (Mewar, Marwar, Dhundhar, Hadoti)",
    section: "खंड- I: राजस्थान सामान्य ज्ञान, इतिहास एवं संस्कृति",
    subSection: "6. समाज और धर्म",
    isCommon: true,
    commonKey: "raj-cult-paintings",
    commonNotes: "CET में चित्रकला शैलियां (किशनगढ़, बनीठनी, कोटा, बूंदी) कॉमन हैं।",
    canonicalTopicId: 26,
    canonicalTopicName: "राजस्थान की चित्रकला शैलियाँ",
    examScope: "BOTH",
  },
  {
    id: "st-soc-5",
    titleHindi: "मेले और त्योहार (Fairs & Festivals of Rajasthan)",
    titleEnglish: "Fairs and Festivals of Rajasthan",
    section: "खंड- I: राजस्थान सामान्य ज्ञान, इतिहास एवं संस्कृति",
    subSection: "6. समाज और धर्म",
    isCommon: true,
    commonKey: "raj-cult-fairs-festivals",
    commonNotes: "CET में मेले व त्योहार शत-प्रतिशत कॉमन टॉपिक है।",
    canonicalTopicId: 21,
    canonicalTopicName: "राजस्थान के मेले",
    examScope: "BOTH",
  },
  {
    id: "st-soc-6",
    titleHindi: "रीति-रिवाज, वेशभूषा, आभूषण और हस्तशिल्प (Customs, Costumes, Ornaments & Handicrafts)",
    titleEnglish: "Customs, Costumes, Ornaments & Handicrafts",
    section: "खंड- I: राजस्थान सामान्य ज्ञान, इतिहास एवं संस्कृति",
    subSection: "6. समाज और धर्म",
    isCommon: true,
    commonKey: "raj-cult-costumes-crafts",
    commonNotes: "CET में वेशभूषा, आभूषण एवं हस्तकलाएं (थेवा, मीनाकारी आदि) कॉमन हैं।",
    canonicalTopicId: 24,
    canonicalTopicName: "राजस्थान की वेशभूषा एवं आभूषण",
    examScope: "BOTH",
  },
  {
    id: "st-soc-7",
    titleHindi: "लोक संगीत, नृत्य और प्रदर्शन कला (Folk Music, Dances & Performing Arts)",
    titleEnglish: "Folk Music, Dance & Performing Arts (Ghoomar, Gair, Terah Taali, etc.)",
    section: "खंड- I: राजस्थान सामान्य ज्ञान, इतिहास एवं संस्कृति",
    subSection: "6. समाज और धर्म",
    isCommon: true,
    commonKey: "raj-cult-music-dance",
    commonNotes: "CET में लोक नृत्य एवं लोक वाद्य यंत्र पूर्णतः कॉमन हैं।",
    canonicalTopicId: 31,
    canonicalTopicName: "राजस्थान के लोक नृत्य",
    examScope: "BOTH",
  },
  {
    id: "st-soc-8",
    titleHindi: "भाषा और साहित्य (Rajasthani Language & Literature)",
    titleEnglish: "Rajasthani Language, Dialects & Literature",
    section: "खंड- I: राजस्थान सामान्य ज्ञान, इतिहास एवं संस्कृति",
    subSection: "6. समाज और धर्म",
    isCommon: true,
    commonKey: "raj-cult-literature",
    commonNotes: "CET में राजस्थानी साहित्य व बोलियां कॉमन हैं।",
    canonicalTopicId: 33,
    canonicalTopicName: "राजस्थानी साहित्य",
    examScope: "BOTH",
  },

  // खंड- I: 7. राजस्थान की प्रमुख हस्तियां
  {
    id: "st-pers-1",
    titleHindi: "राजस्थान की प्रमुख हस्तियां (Major Personalities of Rajasthan)",
    titleEnglish: "Eminent Personalities of Rajasthan",
    section: "खंड- I: राजस्थान सामान्य ज्ञान, इतिहास एवं संस्कृति",
    subSection: "7. प्रमुख हस्तियां",
    isCommon: true,
    commonKey: "raj-personalities",
    commonNotes: "CET में ऐतिहासिक व स्वतंत्रता सेनानी व्यक्तित्व शामिल हैं।",
    canonicalTopicId: 55,
    canonicalTopicName: "राजस्थान के प्रमुख व्यक्तित्व",
    examScope: "BOTH",
  },

  // खंड- I: 8. राजनीतिक और प्रशासनिक व्यवस्था
  {
    id: "st-pol-1",
    titleHindi: "राज्यपाल, मुख्यमंत्री और मंत्रिपरिषद (Governor, CM & Council of Ministers)",
    titleEnglish: "Governor, Chief Minister & Council of Ministers",
    section: "खंड- I: राजस्थान सामान्य ज्ञान, इतिहास एवं संस्कृति",
    subSection: "8. राजनीतिक और प्रशासनिक व्यवस्था",
    isCommon: true,
    commonKey: "raj-pol-exec",
    commonNotes: "CET में राज्य कार्यपालिका (राज्यपाल, सीएम) पूरी तरह कॉमन है।",
    canonicalTopicId: 59,
    canonicalTopicName: "राजस्थान के राज्यपाल",
    examScope: "BOTH",
  },
  {
    id: "st-pol-2",
    titleHindi: "राज्य विधानसभा (Rajasthan Legislative Assembly)",
    titleEnglish: "Rajasthan Legislative Assembly",
    section: "खंड- I: राजस्थान सामान्य ज्ञान, इतिहास एवं संस्कृति",
    subSection: "8. राजनीतिक और प्रशासनिक व्यवस्था",
    isCommon: true,
    commonKey: "raj-pol-assembly",
    commonNotes: "CET में राज्य विधानमंडल कॉमन है।",
    canonicalTopicId: 62,
    canonicalTopicName: "राजस्थान राज्य विधानमंडल",
    examScope: "BOTH",
  },
  {
    id: "st-pol-3",
    titleHindi: "राजस्थान उच्च न्यायालय और अधीनस्थ न्यायालय (High Court & Subordinate Courts)",
    titleEnglish: "Rajasthan High Court & Subordinate Courts",
    section: "खंड- I: राजस्थान सामान्य ज्ञान, इतिहास एवं संस्कृति",
    subSection: "8. राजनीतिक और प्रशासनिक व्यवस्था",
    isCommon: true,
    commonKey: "raj-pol-judiciary",
    commonNotes: "CET में उच्च न्यायालय व राज्य न्यायपालिका कॉमन है।",
    canonicalTopicId: 63,
    canonicalTopicName: "राजस्थान उच्च न्यायालय एवं न्यायपालिका",
    examScope: "BOTH",
  },
  {
    id: "st-pol-4",
    titleHindi: "पंचायती राज व्यवस्था और इसका प्रशासन (Panchayati Raj Administration)",
    titleEnglish: "Panchayati Raj System & Administration",
    section: "खंड- I: राजस्थान सामान्य ज्ञान, इतिहास एवं संस्कृति",
    subSection: "8. राजनीतिक और प्रशासनिक व्यवस्था",
    isCommon: true,
    commonKey: "raj-pol-panchayat",
    commonNotes: "CET में 73वां संविधान संशोधन व पंचायती राज अधिनियम कॉमन है।",
    canonicalTopicId: 65,
    canonicalTopicName: "राजस्थान पंचायती राज",
    examScope: "BOTH",
  },
  {
    id: "st-pol-5",
    titleHindi: "शहरी स्थानीय स्वशासन और इसका प्रशासन (Urban Local Self Government)",
    titleEnglish: "Urban Local Governance (74th Amendment)",
    section: "खंड- I: राजस्थान सामान्य ज्ञान, इतिहास एवं संस्कृति",
    subSection: "8. राजनीतिक और प्रशासनिक व्यवस्था",
    isCommon: true,
    commonKey: "raj-pol-urban",
    commonNotes: "CET में नगरीय स्वशासन एवं नगरपालिकाएं कॉमन है।",
    canonicalTopicId: 74,
    canonicalTopicName: "राजस्थान नगरीय स्वशासन एवं नगरपालिका",
    examScope: "BOTH",
  },
  {
    id: "st-pol-6",
    titleHindi: "राज्य सचिवालय, संभागीय आयुक्त, जिला प्रशासन (Secretariat & District Administration)",
    titleEnglish: "State Secretariat, Divisional Commissioner, District Administration",
    section: "खंड- I: राजस्थान सामान्य ज्ञान, इतिहास एवं संस्कृति",
    subSection: "8. राजनीतिक और प्रशासनिक व्यवस्था",
    isCommon: true,
    commonKey: "raj-pol-admin",
    commonNotes: "CET में मुख्य सचिव, संभागीय व्यवस्था व जिला प्रशासन शामिल है।",
    canonicalTopicId: 64,
    canonicalTopicName: "राजस्थान जिला प्रशासन",
    examScope: "BOTH",
  },
  {
    id: "st-pol-7",
    titleHindi: "प्रमुख आयोग: RPSC, मानवाधिकार, महिला आयोग, वित्त आयोग, निर्वाचन आयोग, लोकायुक्त, RSLSA",
    titleEnglish: "Constitutional & Statutory Commissions (RPSC, SHRC, SEC, Lokayukta, etc.)",
    section: "खंड- I: राजस्थान सामान्य ज्ञान, इतिहास एवं संस्कृति",
    subSection: "8. राजनीतिक और प्रशासनिक व्यवस्था",
    isCommon: true,
    commonKey: "raj-pol-commissions",
    commonNotes: "CET में RPSC, राज्य निर्वाचन आयोग, मानवाधिकार आयोग, लोकायुक्त कॉमन हैं।",
    canonicalTopicId: 66,
    canonicalTopicName: "राजस्थान लोक सेवा आयोग (RPSC)",
    examScope: "BOTH",
  },

  // खंड- II: राजस्थान का समसामयिक घटनाक्रम (Current Affairs)
  {
    id: "st-curr-1",
    titleHindi: "प्रमुख व्यक्ति, स्थान और वर्तमान मुद्दे (Major Persons, Places & Current Issues)",
    titleEnglish: "Current Persons, Places & Issues in Rajasthan",
    section: "खंड- II: राजस्थान का समसामयिक घटनाक्रम",
    subSection: "समसामयिक घटनाक्रम (Current Affairs)",
    isCommon: true,
    commonKey: "curr-persons-places",
    commonNotes: "CET में राज्य, राष्ट्रीय एवं अंतरराष्ट्रीय चर्चित व्यक्ति व स्थान कॉमन हैं।",
    examScope: "BOTH",
  },
  {
    id: "st-curr-2",
    titleHindi: "कल्याण और विकास से संबंधित नई योजनाएं और पहल (Welfare & Development Schemes)",
    titleEnglish: "Welfare & Development Schemes of Rajasthan Govt",
    section: "खंड- II: राजस्थान का समसामयिक घटनाक्रम",
    subSection: "समसामयिक घटनाक्रम (Current Affairs)",
    isCommon: true,
    commonKey: "curr-schemes",
    commonNotes: "CET में फ्लैगशिप योजनाएं, जनकल्याणकारी योजनाएं कॉमन हैं।",
    examScope: "BOTH",
  },
  {
    id: "st-curr-3",
    titleHindi: "आर्थिक-राजनीतिक गतिशीलता (Economic-Political Dynamics)",
    titleEnglish: "Economic-Political Dynamics of Rajasthan",
    section: "खंड- II: राजस्थान का समसामयिक घटनाक्रम",
    subSection: "समसामयिक घटनाक्रम (Current Affairs)",
    isCommon: true,
    commonKey: "curr-eco-dynamics",
    commonNotes: "CET में बजट, आर्थिक समीक्षा व समसामयिक आर्थिक नीतियां समान हैं।",
    canonicalTopicId: 75,
    canonicalTopicName: "राजस्थान का बजट एवं आर्थिक समीक्षा",
    examScope: "BOTH",
  },
  {
    id: "st-curr-4",
    titleHindi: "खेल और क्रीड़ा (Sports and Games in Rajasthan & India)",
    titleEnglish: "Sports & Games, Rajasthan State Games, Medal Winners",
    section: "खंड- II: राजस्थान का समसामयिक घटनाक्रम",
    subSection: "समसामयिक घटनाक्रम (Current Affairs)",
    isCommon: true,
    commonKey: "curr-sports",
    commonNotes: "CET में खेलकूद, राष्ट्रीय खेल व पदक विजेता कॉमन हैं।",
    examScope: "BOTH",
  },
  {
    id: "st-curr-5",
    titleHindi: "पुरस्कार, पुस्तकें और लेखक (Awards, Books & Authors)",
    titleEnglish: "Awards, Honors, Books & Authors",
    section: "खंड- II: राजस्थान का समसामयिक घटनाक्रम",
    subSection: "समसामयिक घटनाक्रम (Current Affairs)",
    isCommon: true,
    commonKey: "curr-awards-books",
    commonNotes: "CET में साहित्य अकादमी पुरस्कार, पद्म पुरस्कार, पुस्तकें कॉमन हैं।",
    examScope: "BOTH",
  },

  // खंड- III: विश्व और भारत का सामान्य ज्ञान
  // 1. विश्व भूगोल
  {
    id: "st-world-1",
    titleHindi: "महाद्वीप, महासागर और उनकी विशेषताएं (Continents & Oceans)",
    titleEnglish: "Continents, Oceans and their Physical Characteristics",
    section: "खंड- III: विश्व और भारत का सामान्य ज्ञान",
    subSection: "1. विश्व भूगोल (World Geography)",
    isCommon: false,
    commonNotes: "Senior Teacher विशेष: CET में विश्व भूगोल के ये विस्तृत टॉपिक नहीं हैं।",
    examScope: "SENIOR_TEACHER",
  },
  {
    id: "st-world-2",
    titleHindi: "वैश्विक पवन तंत्र (Global Wind System)",
    titleEnglish: "Global Wind System & Planetary Winds",
    section: "खंड- III: विश्व और भारत का सामान्य ज्ञान",
    subSection: "1. विश्व भूगोल (World Geography)",
    isCommon: false,
    commonNotes: "Senior Teacher विशेष: CET में पवन तंत्र शामिल नहीं है।",
    examScope: "SENIOR_TEACHER",
  },
  {
    id: "st-world-3",
    titleHindi: "पर्यावरणीय मुद्दे और रणनीतियाँ (Environmental Issues & Strategies)",
    titleEnglish: "Environmental Issues, Global Warming & Conservation",
    section: "खंड- III: विश्व और भारत का सामान्य ज्ञान",
    subSection: "1. विश्व भूगोल (World Geography)",
    isCommon: true,
    commonKey: "env-issues",
    commonNotes: "CET विज्ञान में भी पर्यावरण, पारिस्थितिकी तंत्र एवं जलवायु परिवर्तन शामिल है।",
    examScope: "BOTH",
  },
  {
    id: "st-world-4",
    titleHindi: "प्रमुख मानव व्यवसाय (Major Human Occupations)",
    titleEnglish: "Major Human Occupations Globally",
    section: "खंड- III: विश्व और भारत का सामान्य ज्ञान",
    subSection: "1. विश्व भूगोल (World Geography)",
    isCommon: false,
    commonNotes: "Senior Teacher विशेष टॉपिक।",
    examScope: "SENIOR_TEACHER",
  },
  {
    id: "st-world-5",
    titleHindi: "जनसंख्या वितरण और प्रवास (Population Distribution & Migration)",
    titleEnglish: "Global Population Distribution & Migration Patterns",
    section: "खंड- III: विश्व और भारत का सामान्य ज्ञान",
    subSection: "1. विश्व भूगोल (World Geography)",
    isCommon: false,
    commonNotes: "Senior Teacher विशेष टॉपिक।",
    examScope: "SENIOR_TEACHER",
  },

  // 2. भारत का भूगोल
  {
    id: "st-ind-geo-1",
    titleHindi: "भारत की भौतिक विशेषताएं (Physical Features of India)",
    titleEnglish: "Physical Divisions of India (Himalayas, Plains, Peninsular)",
    section: "खंड- III: विश्व और भारत का सामान्य ज्ञान",
    subSection: "2. भारत का भूगोल (Geography of India)",
    isCommon: true,
    commonKey: "ind-geo-physical",
    commonNotes: "CET में 'भारत के भौतिक स्वरूप: पर्वत, पठार, मरुस्थल एवं मैदान' कॉमन है।",
    examScope: "BOTH",
  },
  {
    id: "st-ind-geo-2",
    titleHindi: "जलवायु तंत्र - मानसून (Climate System & Monsoon)",
    titleEnglish: "Indian Climate System & Monsoon Mechanism",
    section: "खंड- III: विश्व और भारत का सामान्य ज्ञान",
    subSection: "2. भारत का भूगोल (Geography of India)",
    isCommon: true,
    commonKey: "ind-geo-monsoon",
    commonNotes: "CET में मानसून तंत्र एवं जलवायु पर प्रश्न पूछे जाते हैं।",
    examScope: "BOTH",
  },
  {
    id: "st-ind-geo-3",
    titleHindi: "अपवाह तंत्र / नदियाँ (Drainage System & Major Rivers of India)",
    titleEnglish: "Drainage System & Major Rivers of India",
    section: "खंड- III: विश्व और भारत का सामान्य ज्ञान",
    subSection: "2. भारत का भूगोल (Geography of India)",
    isCommon: true,
    commonKey: "ind-geo-rivers",
    commonNotes: "CET में भारत की प्रमुख नदियां, बांध एवं परियोजनाएं कॉमन हैं।",
    examScope: "BOTH",
  },
  {
    id: "st-ind-geo-4",
    titleHindi: "प्राकृतिक वनस्पति और जैव विविधता (Natural Vegetation & Biodiversity)",
    titleEnglish: "Natural Vegetation, Forest Types & Biodiversity",
    section: "खंड- III: विश्व और भारत का सामान्य ज्ञान",
    subSection: "2. भारत का भूगोल (Geography of India)",
    isCommon: true,
    commonKey: "ind-geo-vegetation",
    commonNotes: "CET में वन्यजीव अभयारण्य, राष्ट्रीय उद्यान एवं जैव विविधता कॉमन है।",
    examScope: "BOTH",
  },
  {
    id: "st-ind-geo-5",
    titleHindi: "ऊर्जा संसाधन (Energy Resources of India)",
    titleEnglish: "Conventional & Renewable Energy Resources of India",
    section: "खंड- III: विश्व और भारत का सामान्य ज्ञान",
    subSection: "2. भारत का भूगोल (Geography of India)",
    isCommon: true,
    commonKey: "ind-geo-energy",
    commonNotes: "CET में ऊर्जा संसाधन (पारंपरिक एवं गैर-पारंपरिक) कॉमन है।",
    examScope: "BOTH",
  },

  // 3. भारतीय अर्थव्यवस्था
  {
    id: "st-ind-eco-1",
    titleHindi: "कृषि, उद्योग और सेवा क्षेत्र में वृद्धि और विकास (Growth in Agriculture, Industry & Services)",
    titleEnglish: "Growth & Development in Agri, Industry & Services Sectors",
    section: "खंड- III: विश्व और भारत का सामान्य ज्ञान",
    subSection: "3. भारतीय अर्थव्यवस्था (Indian Economy)",
    isCommon: true,
    commonKey: "ind-eco-sectors",
    commonNotes: "CET स्नातक स्तर में 'कृषि, उद्योग, सेवा एवं व्यापार क्षेत्र' समान रूप से है।",
    examScope: "BOTH",
  },
  {
    id: "st-ind-eco-2",
    titleHindi: "भारत का विदेशी व्यापार: रुझान, संरचना और दिशा (Foreign Trade Trends & Direction)",
    titleEnglish: "India's Foreign Trade: Trends, Composition & Direction",
    section: "खंड- III: विश्व और भारत का सामान्य ज्ञान",
    subSection: "3. भारतीय अर्थव्यवस्था (Indian Economy)",
    isCommon: false,
    commonNotes: "Senior Teacher विशेष: विदेशी व्यापार रुझान विशेष रूप से 2nd Grade में है।",
    examScope: "SENIOR_TEACHER",
  },

  // 4. भारत का संविधान और विदेश नीति
  {
    id: "st-ind-pol-1",
    titleHindi: "संवैधानिक विकास, संविधान सभा और बी.आर. अंबेडकर की भूमिका (Constitutional Development & Ambedkar)",
    titleEnglish: "Constitutional Development, Constituent Assembly & Ambedkar's Role",
    section: "खंड- III: विश्व और भारत का सामान्य ज्ञान",
    subSection: "4. भारत का संविधान और विदेश नीति",
    isCommon: true,
    commonKey: "ind-pol-making",
    commonNotes: "CET में संविधान निर्माण, विशेषताएं एवं दार्शनिक आधार कॉमन है।",
    examScope: "BOTH",
  },
  {
    id: "st-ind-pol-2",
    titleHindi: "नागरिकता, मौलिक अधिकार, राज्य के नीति निर्देशक तत्व, मौलिक कर्तव्य",
    titleEnglish: "Citizenship, Fundamental Rights, DPSP & Fundamental Duties",
    section: "खंड- III: विश्व और भारत का सामान्य ज्ञान",
    subSection: "4. भारत का संविधान और विदेश नीति",
    isCommon: true,
    commonKey: "ind-pol-rights-dpsp",
    commonNotes: "CET में मूल अधिकार, नीति निर्देशक तत्व व मूल कर्तव्य शत-प्रतिशत कॉमन हैं।",
    examScope: "BOTH",
  },
  {
    id: "st-ind-pol-3",
    titleHindi: "राष्ट्रपति, उपराष्ट्रपति, प्रधानमंत्री और मंत्रिपरिषद (President, VP, PM & Cabinet)",
    titleEnglish: "Union Executive: President, Vice-President, PM & Council of Ministers",
    section: "खंड- III: विश्व और भारत का सामान्य ज्ञान",
    subSection: "4. भारत का संविधान और विदेश नीति",
    isCommon: true,
    commonKey: "ind-pol-union-exec",
    commonNotes: "CET में संघीय कार्यपालिका (राष्ट्रपति व प्रधानमंत्री) कॉमन टॉपिक है।",
    examScope: "BOTH",
  },
  {
    id: "st-ind-pol-4",
    titleHindi: "संसद, सर्वोच्च न्यायालय, चुनाव आयोग (Parliament, Supreme Court, Election Commission)",
    titleEnglish: "Parliament, Supreme Court & Election Commission of India",
    section: "खंड- III: विश्व और भारत का सामान्य ज्ञान",
    subSection: "4. भारत का संविधान और विदेश नीति",
    isCommon: true,
    commonKey: "ind-pol-institutions",
    commonNotes: "CET में संसद व उच्चतम न्यायालय समान रूप से शामिल हैं।",
    examScope: "BOTH",
  },
  {
    id: "st-ind-pol-5",
    titleHindi: "विदेश नीति: सिद्धांत एवं जवाहरलाल नेहरू का योगदान (Foreign Policy & Nehru's Contribution)",
    titleEnglish: "Foreign Policy Principles, Non-Alignment & Nehru's Role",
    section: "खंड- III: विश्व और भारत का सामान्य ज्ञान",
    subSection: "4. भारत का संविधान और विदेश नीति",
    isCommon: false,
    commonNotes: "Senior Teacher विशेष: गुटनिरपेक्षता एवं नेहरूजी का विदेश नीति में योगदान।",
    examScope: "SENIOR_TEACHER",
  },
  {
    id: "st-ind-pol-6",
    titleHindi: "प्रमुख शक्तियों और पड़ोसी देशों के साथ भारत के संबंध (Relations with Major Powers & Neighbours)",
    titleEnglish: "India's Relations with Major Powers and Neighbouring Countries",
    section: "खंड- III: विश्व और भारत का सामान्य ज्ञान",
    subSection: "4. भारत का संविधान और विदेश नीति",
    isCommon: false,
    commonNotes: "Senior Teacher विशेष अंतरराष्ट्रीय संबंध टॉपिक।",
    examScope: "SENIOR_TEACHER",
  },
  {
    id: "st-ind-pol-7",
    titleHindi: "समकालीन मुद्दे और चुनौतियां (Contemporary Geopolitical Issues & Challenges)",
    titleEnglish: "Contemporary Global Issues & Challenges in Geopolitics",
    section: "खंड- III: विश्व और भारत का सामान्य ज्ञान",
    subSection: "4. भारत का संविधान और विदेश नीति",
    isCommon: false,
    commonNotes: "Senior Teacher विशेष टॉपिक।",
    examScope: "SENIOR_TEACHER",
  },

  // खंड- IV: शैक्षिक मनोविज्ञान (Educational Psychology - 20 Qs / 40 Marks)
  {
    id: "st-psy-1",
    titleHindi: "शैक्षिक मनोविज्ञान: प्रकृति, क्षेत्र और प्रभावी शिक्षण के लिए निहितार्थ",
    titleEnglish: "Educational Psychology: Nature, Scope & Classroom Implications",
    section: "खंड- IV: शैक्षिक मनोविज्ञान (Educational Psychology)",
    subSection: "शैक्षिक मनोविज्ञान",
    isCommon: false,
    commonNotes: "Senior Teacher विशेष: शिक्षक भर्ती परीक्षा का प्रमुख विषय (20 प्रश्न / 40 अंक)।",
    examScope: "SENIOR_TEACHER",
  },
  {
    id: "st-psy-2",
    titleHindi: "अधिगमकर्ता का समग्र विकास: संज्ञानात्मक, सामाजिक, नैतिक, भावनात्मक, भाषाई और शारीरिक",
    titleEnglish: "Learner's Holistic Development: Cognitive, Social, Moral, Emotional, Physical",
    section: "खंड- IV: शैक्षिक मनोविज्ञान (Educational Psychology)",
    subSection: "शैक्षिक मनोविज्ञान",
    isCommon: false,
    commonNotes: "Senior Teacher विशेष: पियाजे, कोहलबर्ग, वाइगोत्स्की के विकास सिद्धांत।",
    examScope: "SENIOR_TEACHER",
  },
  {
    id: "st-psy-3",
    titleHindi: "अधिगम (Learning): अर्थ, प्रकार, व्यवहारवादी, संज्ञानात्मक, सामाजिक एवं रचनावादी दृष्टिकोण",
    titleEnglish: "Learning Theories: Behaviorist, Cognitive, Social & Constructivist Approaches",
    section: "खंड- IV: शैक्षिक मनोविज्ञान (Educational Psychology)",
    subSection: "शैक्षिक मनोविज्ञान",
    isCommon: false,
    commonNotes: "Senior Teacher विशेष: थार्नडाइक, पावलव, स्किनर, कोहलर, बांडुरा आदि सिद्धांत।",
    examScope: "SENIOR_TEACHER",
  },
  {
    id: "st-psy-4",
    titleHindi: "व्यक्तित्व (Personality): अर्थ, सिद्धांत और मापन; समायोजन और मानसिक स्वास्थ्य",
    titleEnglish: "Personality: Theories, Assessment, Adjustment & Mental Health",
    section: "खंड- IV: शैक्षिक मनोविज्ञान (Educational Psychology)",
    subSection: "शैक्षिक मनोविज्ञान",
    isCommon: false,
    commonNotes: "Senior Teacher विशेष: व्यक्तित्व मापन विधियां व रक्षा युक्तियां।",
    examScope: "SENIOR_TEACHER",
  },
  {
    id: "st-psy-5",
    titleHindi: "बुद्धि और सृजनात्मकता (Intelligence & Creativity): अर्थ, सिद्धांत, मापन एवं संवेगात्मक बुद्धि (EQ)",
    titleEnglish: "Intelligence & Creativity: Theories, Measurement & Emotional Intelligence (EQ)",
    section: "खंड- IV: शैक्षिक मनोविज्ञान (Educational Psychology)",
    subSection: "शैक्षिक मनोविज्ञान",
    isCommon: false,
    commonNotes: "Senior Teacher विशेष: गार्डनर का बहुबुद्धि सिद्धांत, डेनियल गोलमैन का EQ।",
    examScope: "SENIOR_TEACHER",
  },
  {
    id: "st-psy-6",
    titleHindi: "अभिप्रेरणा (Motivation): अर्थ, प्रकार, सिद्धांत और शिक्षण-अधिगम के लिए निहितार्थ",
    titleEnglish: "Motivation: Meaning, Types, Theories (Maslow, etc.) & Implications",
    section: "खंड- IV: शैक्षिक मनोविज्ञान (Educational Psychology)",
    subSection: "शैक्षिक मनोविज्ञान",
    isCommon: false,
    commonNotes: "Senior Teacher विशेष: मैस्लो आवश्यकता पदानुक्रम व शिक्षण अभिप्रेरणा।",
    examScope: "SENIOR_TEACHER",
  },
  {
    id: "st-psy-7",
    titleHindi: "व्यक्तिगत विभिन्नताएं (Individual Differences) और समावेशी शिक्षा (Inclusive Education)",
    titleEnglish: "Individual Differences & Inclusive Education (Special Needs Children)",
    section: "खंड- IV: शैक्षिक मनोविज्ञान (Educational Psychology)",
    subSection: "शैक्षिक मनोविज्ञान",
    isCommon: false,
    commonNotes: "Senior Teacher विशेष: विशिष्ट बालकों की पहचान व समावेशी शिक्षा।",
    examScope: "SENIOR_TEACHER",
  },
  {
    id: "st-psy-8",
    titleHindi: "21वीं सदी के कौशल का विकास: अवधारणा और रणनीतियाँ",
    titleEnglish: "Development of 21st Century Skills: Concepts & Classroom Strategies",
    section: "खंड- IV: शैक्षिक मनोविज्ञान (Educational Psychology)",
    subSection: "शैक्षिक मनोविज्ञान",
    isCommon: false,
    commonNotes: "Senior Teacher विशेष: महत्वपूर्ण कौशल (Critical Thinking, Communication, Creativity)।",
    examScope: "SENIOR_TEACHER",
  },
];

// ─────────────────────────────────────────────────────────────────────────────
// 2. RSMSSB CET (Common Eligibility Test) Syllabus
// ─────────────────────────────────────────────────────────────────────────────
export const CET_SYLLABUS: SyllabusTopicItem[] = [
  // विषय 1: राजस्थान का इतिहास, कला, संस्कृति, साहित्य एवं विरासत
  {
    id: "cet-art-1",
    titleHindi: "प्राचीन सभ्यताएं: कालीबंगा, आहड़, गणेश्वर, बालाथल और बैराठ",
    titleEnglish: "Ancient Civilizations: Kalibanga, Ahar, Ganeshwar, Balathal, Bairath",
    section: "1. राजस्थान का इतिहास, कला, संस्कृति एवं विरासत",
    subSection: "प्राचीन सभ्यताएं एवं इतिहास",
    isCommon: true,
    commonKey: "raj-hist-ancient-sites",
    commonNotes: "वरिष्ठ अध्यापक (2nd Grade) में भी प्राचीन सभ्यताएं कॉमन हैं।",
    canonicalTopicId: 37,
    canonicalTopicName: "राजस्थान की प्राचीन सभ्यताएँ एवं पुरातात्विक स्थल",
    examScope: "BOTH",
  },
  {
    id: "cet-art-2",
    titleHindi: "प्रमुख राजवंश एवं उनकी प्रशासनिक व राजस्व व्यवस्था",
    titleEnglish: "Major Dynasties, Administrative & Revenue Systems",
    section: "1. राजस्थान का इतिहास, कला, संस्कृति एवं विरासत",
    subSection: "राजपूत काल व रियासतें",
    isCommon: true,
    commonKey: "raj-hist-dynasties",
    commonNotes: "वरिष्ठ अध्यापक में राजपूत राजवंश, दिल्ली सल्तनत व मुगल संबंध कॉमन हैं।",
    canonicalTopicId: 40,
    canonicalTopicName: "राजस्थान का राजपूत काल",
    examScope: "BOTH",
  },
  {
    id: "cet-art-3",
    titleHindi: "स्थापत्य कला की प्रमुख विशेषताएं: किले एवं स्मारक, कलाएं, चित्रकलाएं और हस्तशिल्प",
    titleEnglish: "Architecture: Forts, Monuments, Painting Styles & Handicrafts",
    section: "1. राजस्थान का इतिहास, कला, संस्कृति एवं विरासत",
    subSection: "कला एवं संस्कृति",
    isCommon: true,
    commonKey: "raj-cult-architecture",
    commonNotes: "वरिष्ठ अध्यापक पेपर-1 में किले, मंदिर, शैलियां, हस्तशिल्प पूर्णतः शामिल हैं।",
    canonicalTopicId: 25,
    canonicalTopicName: "राजस्थान की स्थापत्य कला एवं वास्तुकला",
    examScope: "BOTH",
  },
  {
    id: "cet-art-4",
    titleHindi: "मेले, त्यौहार, लोक संगीत एवं लोक नृत्य",
    titleEnglish: "Fairs, Festivals, Folk Music & Folk Dances",
    section: "1. राजस्थान का इतिहास, कला, संस्कृति एवं विरासत",
    subSection: "लोक संस्कृति एवं कला",
    isCommon: true,
    commonKey: "raj-cult-fairs-festivals",
    commonNotes: "वरिष्ठ अध्यापक में मेले, त्योहार, लोक संगीत व नृत्य हूबहू समान हैं।",
    canonicalTopicId: 21,
    canonicalTopicName: "राजस्थान के मेले",
    examScope: "BOTH",
  },
  {
    id: "cet-art-5",
    titleHindi: "राजस्थानी संस्कृति, परंपरा, रीति-रिवाज, वेशभूषा एवं आभूषण",
    titleEnglish: "Traditions, Customs, Costumes & Ornaments",
    section: "1. राजस्थान का इतिहास, कला, संस्कृति एवं विरासत",
    subSection: "संस्कृति एवं रीति-रिवाज",
    isCommon: true,
    commonKey: "raj-cult-costumes-crafts",
    commonNotes: "वरिष्ठ अध्यापक में वेशभूषा, आभूषण व परंपराएं शत-प्रतिशत कॉमन हैं।",
    canonicalTopicId: 24,
    canonicalTopicName: "राजस्थान की वेशभूषा एवं आभूषण",
    examScope: "BOTH",
  },
  {
    id: "cet-art-6",
    titleHindi: "राजस्थान के धार्मिक आंदोलन, संत एवं लोक देवता",
    titleEnglish: "Religious Movements, Saints & Folk Deities",
    section: "1. राजस्थान का इतिहास, कला, संस्कृति एवं विरासत",
    subSection: "धर्म एवं संप्रदाय",
    isCommon: true,
    commonKey: "raj-cult-deities",
    commonNotes: "वरिष्ठ अध्यापक में लोक देवता एवं संत कॉमन टॉपिक हैं।",
    canonicalTopicId: 28,
    canonicalTopicName: "राजस्थान के लोक देवता एवं लोक देवियाँ",
    examScope: "BOTH",
  },
  {
    id: "cet-art-7",
    titleHindi: "राजस्थानी भाषा एवं साहित्य की महत्वपूर्ण कृतियां, क्षेत्रीय बोलियां",
    titleEnglish: "Rajasthani Literature, Works & Dialects",
    section: "1. राजस्थान का इतिहास, कला, संस्कृति एवं विरासत",
    subSection: "भाषा एवं साहित्य",
    isCommon: true,
    commonKey: "raj-cult-literature",
    commonNotes: "वरिष्ठ अध्यापक में भाषा, बोलियां एवं साहित्य कॉमन है।",
    canonicalTopicId: 33,
    canonicalTopicName: "राजस्थानी साहित्य",
    examScope: "BOTH",
  },
  {
    id: "cet-art-8",
    titleHindi: "1857 की क्रांति, किसान एवं जनजातीय आंदोलन, प्रजामंडल आंदोलन",
    titleEnglish: "1857 Revolt, Peasant & Tribal Movements, Prajamandal",
    section: "1. राजस्थान का इतिहास, कला, संस्कृति एवं विरासत",
    subSection: "स्वतंत्रता आंदोलन",
    isCommon: true,
    commonKey: "raj-hist-1857",
    commonNotes: "वरिष्ठ अध्यापक के स्वतंत्रता संग्राम भाग से शत-प्रतिशत समान है।",
    canonicalTopicId: 49,
    canonicalTopicName: "राजस्थान में 1857 का विद्रोह",
    examScope: "BOTH",
  },
  {
    id: "cet-art-9",
    titleHindi: "राजस्थान का एकीकरण (Integration of Rajasthan)",
    titleEnglish: "Integration of Rajasthan",
    section: "1. राजस्थान का इतिहास, कला, संस्कृति एवं विरासत",
    subSection: "आधुनिक इतिहास",
    isCommon: true,
    commonKey: "raj-hist-integration",
    commonNotes: "वरिष्ठ अध्यापक में एकीकरण (सातों चरण) कॉमन है।",
    canonicalTopicId: 54,
    canonicalTopicName: "राजस्थान का एकीकरण",
    examScope: "BOTH",
  },
  {
    id: "cet-art-10",
    titleHindi: "राजस्थान के प्रमुख व्यक्तित्व एवं ऐतिहासिक स्थल",
    titleEnglish: "Eminent Personalities & Historical Sites of Rajasthan",
    section: "1. राजस्थान का इतिहास, कला, संस्कृति एवं विरासत",
    subSection: "प्रमुख व्यक्तित्व",
    isCommon: true,
    commonKey: "raj-personalities",
    commonNotes: "वरिष्ठ अध्यापक में प्रमुख हस्तियां कॉमन टॉपिक है।",
    canonicalTopicId: 55,
    canonicalTopicName: "राजस्थान के प्रमुख व्यक्तित्व",
    examScope: "BOTH",
  },

  // विषय 2: भारत एवं राजस्थान का भूगोल
  {
    id: "cet-geo-1",
    titleHindi: "भारत के भौतिक स्वरूप: पर्वत, पठार, मरुस्थल एवं मैदान",
    titleEnglish: "Physical Features of India: Mountains, Plateaus, Deserts, Plains",
    section: "2. भारत एवं राजस्थान का भूगोल",
    subSection: "भारत का भूगोल",
    isCommon: true,
    commonKey: "ind-geo-physical",
    commonNotes: "वरिष्ठ अध्यापक पेपर-1 के भारत भूगोल में समान रूप से है।",
    examScope: "BOTH",
  },
  {
    id: "cet-geo-2",
    titleHindi: "भारत की प्रमुख नदियां, बांध, वन्यजीव एवं अभयारण्य",
    titleEnglish: "Major Rivers, Dams, Wildlife & Sanctuaries of India",
    section: "2. भारत एवं राजस्थान का भूगोल",
    subSection: "भारत का भूगोल",
    isCommon: true,
    commonKey: "ind-geo-rivers",
    commonNotes: "वरिष्ठ अध्यापक में भारत का अपवाह तंत्र व वनस्पति कॉमन है।",
    examScope: "BOTH",
  },
  {
    id: "cet-geo-3",
    titleHindi: "राजस्थान के भौतिक स्वरूप (भू-आकृतिक प्रदेश) एवं जलवायु दशाएं",
    titleEnglish: "Physiographic Divisions & Climate of Rajasthan",
    section: "2. भारत एवं राजस्थान का भूगोल",
    subSection: "राजस्थान का भूगोल",
    isCommon: true,
    commonKey: "raj-geo-physical",
    commonNotes: "वरिष्ठ अध्यापक में भौतिक विशेषताएं व जलवायु कॉमन हैं।",
    canonicalTopicId: 2,
    canonicalTopicName: "राजस्थान का भौतिक स्वरूप एवं भूगोल",
    examScope: "BOTH",
  },
  {
    id: "cet-geo-4",
    titleHindi: "राजस्थान का अपवाह तंत्र: नदियां, बांध एवं झीलें",
    titleEnglish: "Drainage System, Rivers, Dams & Lakes of Rajasthan",
    section: "2. भारत एवं राजस्थान का भूगोल",
    subSection: "राजस्थान का भूगोल",
    isCommon: true,
    commonKey: "raj-geo-rivers",
    commonNotes: "वरिष्ठ अध्यापक में अपवाह तंत्र व झीलें कॉमन हैं।",
    canonicalTopicId: 7,
    canonicalTopicName: "राजस्थान की नदियाँ एवं जल संसाधन",
    examScope: "BOTH",
  },
  {
    id: "cet-geo-5",
    titleHindi: "राजस्थान की वनस्पति, मृदा, वन्यजीव एवं अभयारण्य",
    titleEnglish: "Vegetation, Soils, Wildlife & Sanctuaries of Rajasthan",
    section: "2. भारत एवं राजस्थान का भूगोल",
    subSection: "राजस्थान का भूगोल",
    isCommon: true,
    commonKey: "raj-geo-vegetation",
    commonNotes: "वरिष्ठ अध्यापक में प्राकृतिक वनस्पति व अभयारण्य कॉमन हैं।",
    canonicalTopicId: 10,
    canonicalTopicName: "राजस्थान के वन एवं वन्यजीव",
    examScope: "BOTH",
  },
  {
    id: "cet-geo-6",
    titleHindi: "राजस्थान की प्रमुख फसलें, कृषि एवं सिंचाई परियोजनाएं",
    titleEnglish: "Major Crops, Agriculture & Irrigation Projects",
    section: "2. भारत एवं राजस्थान का भूगोल",
    subSection: "राजस्थान का भूगोल",
    isCommon: true,
    commonKey: "raj-geo-agri",
    commonNotes: "वरिष्ठ अध्यापक में कृषि व सिंचाई परियोजनाएं कॉमन हैं।",
    canonicalTopicId: 13,
    canonicalTopicName: "राजस्थान की कृषि",
    examScope: "BOTH",
  },
  {
    id: "cet-geo-7",
    titleHindi: "राजस्थान की खनिज संपदा (धात्विक एवं अधात्विक खनिज)",
    titleEnglish: "Mineral Wealth of Rajasthan (Metallic & Non-Metallic)",
    section: "2. भारत एवं राजस्थान का भूगोल",
    subSection: "राजस्थान का भूगोल",
    isCommon: true,
    commonNotes: "राजस्थान GK का मुख्य हिस्सा (Master Topic 15)।",
    canonicalTopicId: 15,
    canonicalTopicName: "राजस्थान के खनिज संसाधन",
    examScope: "CET",
  },
  {
    id: "cet-geo-8",
    titleHindi: "राजस्थान के ऊर्जा संसाधन (परंपरागत एवं गैर-परंपरागत)",
    titleEnglish: "Energy Resources of Rajasthan (Conventional & Non-conventional)",
    section: "2. भारत एवं राजस्थान का भूगोल",
    subSection: "राजस्थान का भूगोल",
    isCommon: true,
    commonKey: "ind-geo-energy",
    commonNotes: "वरिष्ठ अध्यापक भारत GK व राजस्थान Master Topic 16 में शामिल।",
    canonicalTopicId: 16,
    canonicalTopicName: "राजस्थान के ऊर्जा संसाधन",
    examScope: "BOTH",
  },
  {
    id: "cet-geo-9",
    titleHindi: "राजस्थान की जनसंख्या: वृद्धि, घनत्व, साक्षरता, लिंगानुपात एवं प्रमुख जनजातियां",
    titleEnglish: "Demographics & Major Tribes of Rajasthan",
    section: "2. भारत एवं राजस्थान का भूगोल",
    subSection: "राजस्थान का भूगोल",
    isCommon: true,
    commonKey: "raj-geo-demography",
    commonNotes: "वरिष्ठ अध्यापक में जनसांख्यिकी व जनजातियां पूर्णतः कॉमन हैं।",
    canonicalTopicId: 5,
    canonicalTopicName: "राजस्थान की जनसंख्या एवं जनगणना",
    examScope: "BOTH",
  },
  {
    id: "cet-geo-10",
    titleHindi: "राजस्थान के पर्यटन स्थल एवं पर्यटन परिपथ (Circuits)",
    titleEnglish: "Tourist Places & Circuits of Rajasthan",
    section: "2. भारत एवं राजस्थान का भूगोल",
    subSection: "राजस्थान का भूगोल",
    isCommon: true,
    commonKey: "raj-geo-tourism",
    commonNotes: "वरिष्ठ अध्यापक में पर्यटन व प्रमुख पर्यटन केंद्र समान हैं।",
    canonicalTopicId: 19,
    canonicalTopicName: "राजस्थान का पर्यटन",
    examScope: "BOTH",
  },
  {
    id: "cet-geo-11",
    titleHindi: "राजस्थान में यातायात के साधन (सड़क, रेल, वायु परिवहन)",
    titleEnglish: "Transportation in Rajasthan (Road, Rail, Air)",
    section: "2. भारत एवं राजस्थान का भूगोल",
    subSection: "राजस्थान का भूगोल",
    isCommon: true,
    canonicalTopicId: 18,
    canonicalTopicName: "राजस्थान का परिवहन",
    examScope: "CET",
  },

  // विषय 3: भारतीय राजनीतिक व्यवस्था एवं राजस्थान का प्रशासन
  {
    id: "cet-pol-1",
    titleHindi: "भारतीय संविधान: प्रस्तावना, मौलिक अधिकार, नीति निर्देशक तत्व एवं मौलिक कर्तव्य",
    titleEnglish: "Indian Constitution: Preamble, Fundamental Rights, DPSP, Duties",
    section: "3. भारतीय राजनीतिक व्यवस्था एवं राजस्थान प्रशासन",
    subSection: "भारतीय संविधान",
    isCommon: true,
    commonKey: "ind-pol-rights-dpsp",
    commonNotes: "वरिष्ठ अध्यापक पेपर-1 के संविधान भाग में हूबहू कॉमन है।",
    examScope: "BOTH",
  },
  {
    id: "cet-pol-2",
    titleHindi: "संघीय ढांचा: राष्ट्रपति, प्रधानमंत्री, संसद एवं उच्चतम न्यायालय",
    titleEnglish: "Federal Structure: President, PM, Parliament & Supreme Court",
    section: "3. भारतीय राजनीतिक व्यवस्था एवं राजस्थान प्रशासन",
    subSection: "भारतीय राजव्यवस्था",
    isCommon: true,
    commonKey: "ind-pol-union-exec",
    commonNotes: "वरिष्ठ अध्यापक के भारत संविधान भाग में समान रूप से है।",
    examScope: "BOTH",
  },
  {
    id: "cet-pol-3",
    titleHindi: "राजस्थान राज्य प्रशासन: राज्यपाल, मुख्यमंत्री, मंत्रिपरिषद एवं विधानसभा",
    titleEnglish: "Rajasthan State Admin: Governor, CM, Cabinet & Assembly",
    section: "3. भारतीय राजनीतिक व्यवस्था एवं राजस्थान प्रशासन",
    subSection: "राजस्थान राजव्यवस्था",
    isCommon: true,
    commonKey: "raj-pol-exec",
    commonNotes: "वरिष्ठ अध्यापक में राज्यपाल, सीएम, मंत्रिपरिषद व विधानसभा कॉमन हैं।",
    canonicalTopicId: 59,
    canonicalTopicName: "राजस्थान के राज्यपाल",
    examScope: "BOTH",
  },
  {
    id: "cet-pol-4",
    titleHindi: "राजस्थान उच्च न्यायालय, जिला प्रशासन एवं मुख्य सचिव",
    titleEnglish: "Rajasthan High Court, District Admin & Chief Secretary",
    section: "3. भारतीय राजनीतिक व्यवस्था एवं राजस्थान प्रशासन",
    subSection: "राजस्थान राजव्यवस्था",
    isCommon: true,
    commonKey: "raj-pol-judiciary",
    commonNotes: "वरिष्ठ अध्यापक में उच्च न्यायालय व जिला प्रशासन कॉमन है।",
    canonicalTopicId: 63,
    canonicalTopicName: "राजस्थान उच्च न्यायालय एवं न्यायपालिका",
    examScope: "BOTH",
  },
  {
    id: "cet-pol-5",
    titleHindi: "स्थानीय स्वशासन एवं पंचायती राज (73वां व 74वां संविधान संशोधन)",
    titleEnglish: "Local Self Government & Panchayati Raj",
    section: "3. भारतीय राजनीतिक व्यवस्था एवं राजस्थान प्रशासन",
    subSection: "स्थानीय स्वशासन",
    isCommon: true,
    commonKey: "raj-pol-panchayat",
    commonNotes: "वरिष्ठ अध्यापक में पंचायती राज व नगरीय स्वशासन शत-प्रतिशत समान है।",
    canonicalTopicId: 65,
    canonicalTopicName: "राजस्थान पंचायती राज",
    examScope: "BOTH",
  },
  {
    id: "cet-pol-6",
    titleHindi: "राजस्थान के प्रमुख आयोग: RPSC, राज्य निर्वाचन, मानवाधिकार आयोग, लोकायुक्त, सूचना आयोग",
    titleEnglish: "State Commissions: RPSC, SEC, SHRC, Lokayukta, SIC",
    section: "3. भारतीय राजनीतिक व्यवस्था एवं राजस्थान प्रशासन",
    subSection: "संवैधानिक व सांविधिक आयोग",
    isCommon: true,
    commonKey: "raj-pol-commissions",
    commonNotes: "वरिष्ठ अध्यापक में आयोग समान रूप से शामिल हैं।",
    canonicalTopicId: 66,
    canonicalTopicName: "राजस्थान लोक सेवा आयोग (RPSC)",
    examScope: "BOTH",
  },

  // विषय 4: भारत एवं राजस्थान की अर्थव्यवस्था
  {
    id: "cet-eco-1",
    titleHindi: "भारत में बजट निर्माण, बैंकिंग, लोक-वित्त, वस्तु एवं सेवा कर (GST), राष्ट्रीय आय",
    titleEnglish: "Budgeting, Banking, Public Finance, GST, National Income",
    section: "4. भारत एवं राजस्थान की अर्थव्यवस्था",
    subSection: "भारतीय अर्थव्यवस्था",
    isCommon: false,
    commonNotes: "CET स्नातक स्तर विशेष: बैंकिंग व वित्तीय संस्थाओं के प्रश्न।",
    examScope: "CET",
  },
  {
    id: "cet-eco-2",
    titleHindi: "भारत में कृषि, उद्योग, सेवा एवं व्यापार क्षेत्र की पहल एवं योजनाएं",
    titleEnglish: "Sectors of Economy: Agriculture, Industry, Services & Trade",
    section: "4. भारत एवं राजस्थान की अर्थव्यवस्था",
    subSection: "भारतीय अर्थव्यवस्था",
    isCommon: true,
    commonKey: "ind-eco-sectors",
    commonNotes: "वरिष्ठ अध्यापक में कृषि, उद्योग व सेवा क्षेत्र विकास शामिल है।",
    examScope: "BOTH",
  },
  {
    id: "cet-eco-3",
    titleHindi: "राजस्थान की खाद्य एवं व्यावसायिक फसलें, कृषि आधारित उद्योग",
    titleEnglish: "Food & Cash Crops of Rajasthan, Agro-based Industries",
    section: "4. भारत एवं राजस्थान की अर्थव्यवस्था",
    subSection: "राजस्थान अर्थव्यवस्था",
    isCommon: true,
    commonKey: "raj-geo-agri",
    commonNotes: "वरिष्ठ अध्यापक में कृषि व उद्योग कॉमन हैं।",
    canonicalTopicId: 13,
    canonicalTopicName: "राजस्थान की कृषि",
    examScope: "BOTH",
  },
  {
    id: "cet-eco-4",
    titleHindi: "राजस्थान की प्रमुख सिंचाई परियोजनाएं एवं मरुभूमि विकास कार्यक्रम",
    titleEnglish: "Major Irrigation & Desert Development Projects (CAD, DDP)",
    section: "4. भारत एवं राजस्थान की अर्थव्यवस्था",
    subSection: "राजस्थान अर्थव्यवस्था",
    isCommon: true,
    commonNotes: "राजस्थान GK Master Topic 9 (सिंचाई परियोजनाएं) व 12 (मरुस्थलीकरण)।",
    canonicalTopicId: 9,
    canonicalTopicName: "राजस्थान की सिंचाई एवं सिंचाई परियोजनाएँ",
    examScope: "BOTH",
  },
  {
    id: "cet-eco-5",
    titleHindi: "राजस्थान के प्रमुख उद्योग एवं विकास संस्थाएं (RIICO, RFC, RAJSICO)",
    titleEnglish: "Industrial Development Institutions: RIICO, RFC, RAJSICO",
    section: "4. भारत एवं राजस्थान की अर्थव्यवस्था",
    subSection: "राजस्थान अर्थव्यवस्था",
    isCommon: true,
    commonKey: "raj-geo-industries",
    commonNotes: "वरिष्ठ अध्यापक में राजस्थान के उद्योग शामिल हैं।",
    canonicalTopicId: 17,
    canonicalTopicName: "राजस्थान के प्रमुख उद्योग",
    examScope: "BOTH",
  },
  {
    id: "cet-eco-6",
    titleHindi: "राजस्थान में निर्धनता, बेरोजगारी एवं सामाजिक न्याय और कल्याणकारी योजनाएं",
    titleEnglish: "Poverty, Unemployment & Welfare Schemes in Rajasthan",
    section: "4. भारत एवं राजस्थान की अर्थव्यवस्था",
    subSection: "राजस्थान अर्थव्यवस्था",
    isCommon: true,
    commonKey: "curr-schemes",
    commonNotes: "वरिष्ठ अध्यापक के समसामयिक कल्याणकारी योजनाओं से जुड़ा है।",
    canonicalTopicId: 75,
    canonicalTopicName: "राजस्थान का बजट एवं आर्थिक समीक्षा",
    examScope: "BOTH",
  },

  // विषय 5: दैनिक विज्ञान एवं प्रौद्योगिकी (General Science & Technology)
  {
    id: "cet-sci-1",
    titleHindi: "भौतिक एवं रासायनिक परिवर्तन, धातु, अधातु एवं प्रमुख यौगिक",
    titleEnglish: "Physical & Chemical Changes, Metals & Non-Metals, Compounds",
    section: "5. दैनिक विज्ञान एवं प्रौद्योगिकी",
    subSection: "रसायन एवं भौतिक विज्ञान",
    isCommon: false,
    commonNotes: "CET विशेष विषय: दैनिक विज्ञान के प्रश्न।",
    examScope: "CET",
  },
  {
    id: "cet-sci-2",
    titleHindi: "प्रकाश का परावर्तन, लेंस, विद्युत धारा एवं ओम का नियम",
    titleEnglish: "Optics, Reflection, Lenses, Electric Current & Ohm's Law",
    section: "5. दैनिक विज्ञान एवं प्रौद्योगिकी",
    subSection: "भौतिक विज्ञान",
    isCommon: false,
    commonNotes: "CET विशेष विषय।",
    examScope: "CET",
  },
  {
    id: "cet-sci-3",
    titleHindi: "अंतरिक्ष एवं सूचना प्रौद्योगिकी (Space & Information Technology)",
    titleEnglish: "Space & Information Technology (ISRO, Satellites, IT)",
    section: "5. दैनिक विज्ञान एवं प्रौद्योगिकी",
    subSection: "प्रौद्योगिकी",
    isCommon: false,
    commonNotes: "CET विशेष विषय।",
    canonicalTopicId: 73,
    canonicalTopicName: "राजस्थान विज्ञान एवं प्रौद्योगिकी",
    examScope: "CET",
  },
  {
    id: "cet-sci-4",
    titleHindi: "आनुवंशिकी (Genetics), मेंडल के नियम, डीएनए/आरएनए एवं रक्त समूह",
    titleEnglish: "Genetics, Mendel's Laws, DNA/RNA & Blood Groups",
    section: "5. दैनिक विज्ञान एवं प्रौद्योगिकी",
    subSection: "जीव विज्ञान",
    isCommon: false,
    commonNotes: "CET विशेष विषय।",
    examScope: "CET",
  },
  {
    id: "cet-sci-5",
    titleHindi: "मानव रोग: कारण एवं निवारण, पोषण एवं संतुलित आहार",
    titleEnglish: "Human Diseases: Causes & Prevention, Nutrition & Diet",
    section: "5. दैनिक विज्ञान एवं प्रौद्योगिकी",
    subSection: "स्वास्थ्य एवं पोषण",
    isCommon: false,
    commonNotes: "CET विशेष विषय।",
    examScope: "CET",
  },
  {
    id: "cet-sci-6",
    titleHindi: "पर्यावरण अध्ययन, पारिस्थितिकी तंत्र एवं जैव विविधता संरक्षण",
    titleEnglish: "Environmental Studies, Ecosystem & Biodiversity Conservation",
    section: "5. दैनिक विज्ञान एवं प्रौद्योगिकी",
    subSection: "पर्यावरण",
    isCommon: true,
    commonKey: "env-issues",
    commonNotes: "वरिष्ठ अध्यापक पेपर-1 के विश्व पर्यावरण भाग में भी शामिल है।",
    examScope: "BOTH",
  },

  // विषय 6: तार्किक विवेचन एवं मानसिक योग्यता (Reasoning & Mental Ability / Basic Math)
  {
    id: "cet-reas-1",
    titleHindi: "सादृश्यता, वर्गीकरण, श्रृंखला एवं कोडिंग-डिकोडिंग (Analogy, Series, Coding)",
    titleEnglish: "Analogy, Classification, Series & Coding-Decoding",
    section: "6. तार्किक विवेचन एवं मानसिक योग्यता",
    subSection: "तार्किक विवेचन (Reasoning)",
    isCommon: false,
    commonNotes: "CET विशेष विषय (Senior Teacher Paper-1 में नहीं है)।",
    examScope: "CET",
  },
  {
    id: "cet-reas-2",
    titleHindi: "रक्त संबंध, दिशा ज्ञान परीक्षण, बैठक व्यवस्था (Blood Relations, Direction, Seating)",
    titleEnglish: "Blood Relations, Direction Sense Test, Seating Arrangement",
    section: "6. तार्किक विवेचन एवं मानसिक योग्यता",
    subSection: "तार्किक विवेचन (Reasoning)",
    isCommon: false,
    commonNotes: "CET विशेष विषय।",
    examScope: "CET",
  },
  {
    id: "cet-reas-3",
    titleHindi: "वेन आरेख, न्याय वाक्य, कथन एवं निष्कर्ष (Venn Diagrams, Syllogism, Statements)",
    titleEnglish: "Venn Diagrams, Syllogisms, Arguments & Assumptions",
    section: "6. तार्किक विवेचन एवं मानसिक योग्यता",
    subSection: "तार्किक विवेचन (Reasoning)",
    isCommon: false,
    commonNotes: "CET विशेष विषय।",
    examScope: "CET",
  },
  {
    id: "cet-reas-4",
    titleHindi: "प्रतिशत, लाभ एवं हानि, छूट (Percentage, Profit & Loss, Discount)",
    titleEnglish: "Basic Numeracy: Percentage, Profit & Loss, Discount",
    section: "6. तार्किक विवेचन एवं मानसिक योग्यता",
    subSection: "आधारभूत गणित (Maths)",
    isCommon: false,
    commonNotes: "CET विशेष विषय।",
    examScope: "CET",
  },
  {
    id: "cet-reas-5",
    titleHindi: "अनुपात एवं समानुपात, औसत, साधारण एवं चक्रवृद्धि ब्याज",
    titleEnglish: "Ratio & Proportion, Average, Simple & Compound Interest",
    section: "6. तार्किक विवेचन एवं मानसिक योग्यता",
    subSection: "आधारभूत गणित (Maths)",
    isCommon: false,
    commonNotes: "CET विशेष विषय।",
    examScope: "CET",
  },
  {
    id: "cet-reas-6",
    titleHindi: "क्षेत्रमिति: त्रिभुज, वृत्त, आयत, बेलन, शंकु का क्षेत्रफल एवं आयतन",
    titleEnglish: "Mensuration: Area & Volume of Triangles, Circles, Cylinders",
    section: "6. तार्किक विवेचन एवं मानसिक योग्यता",
    subSection: "आधारभूत गणित (Maths)",
    isCommon: false,
    commonNotes: "CET विशेष विषय।",
    examScope: "CET",
  },

  // विषय 7: सामान्य हिन्दी (General Hindi)
  {
    id: "cet-hin-1",
    titleHindi: "संधि और संधि विच्छेद, सामासिक पदों की रचना और समास विग्रह",
    titleEnglish: "Sandhi & Samas (Compound Words & Splitting)",
    section: "7. सामान्य हिन्दी (General Hindi)",
    subSection: "व्याकरण",
    isCommon: false,
    commonNotes: "CET विशेष विषय (Senior Teacher Paper-1 में भाषा व्याकरण नहीं है)।",
    examScope: "CET",
  },
  {
    id: "cet-hin-2",
    titleHindi: "उपसर्ग, प्रत्यय, पर्यायवाची एवं विलोम शब्द",
    titleEnglish: "Prefix, Suffix, Synonyms & Antonyms",
    section: "7. सामान्य हिन्दी (General Hindi)",
    subSection: "शब्दावली",
    isCommon: false,
    commonNotes: "CET विशेष विषय।",
    examScope: "CET",
  },
  {
    id: "cet-hin-3",
    titleHindi: "शब्द शुद्धि एवं वाक्य शुद्धि, शब्द युग्म, अनेकार्थक शब्द",
    titleEnglish: "Word & Sentence Correction, Word Pairs, Homonyms",
    section: "7. सामान्य हिन्दी (General Hindi)",
    subSection: "शुद्धि एवं शब्दावली",
    isCommon: false,
    commonNotes: "CET विशेष विषय।",
    examScope: "CET",
  },
  {
    id: "cet-hin-4",
    titleHindi: "वाक्यांश के लिए एक शब्द, मुहावरे और लोकोक्तियां",
    titleEnglish: "One Word Substitution, Idioms & Proverbs",
    section: "7. सामान्य हिन्दी (General Hindi)",
    subSection: "मुहावरे एवं वाक्यांश",
    isCommon: false,
    commonNotes: "CET विशेष विषय।",
    canonicalTopicId: 35,
    canonicalTopicName: "राजस्थानी मुहावरे एवं लोकोक्तियाँ",
    examScope: "CET",
  },
  {
    id: "cet-hin-5",
    titleHindi: "पारिभाषिक शब्दावली (अंग्रेजी शब्दों के समकक्ष हिंदी शब्द) एवं कार्यालयी पत्र",
    titleEnglish: "Administrative Terminology & Official Letter Writing",
    section: "7. सामान्य हिन्दी (General Hindi)",
    subSection: "कार्यालयी ज्ञान",
    isCommon: false,
    commonNotes: "CET विशेष विषय।",
    examScope: "CET",
  },

  // विषय 8: General English
  {
    id: "cet-eng-1",
    titleHindi: "Tenses / Sequence of Tenses, Voice (Active & Passive)",
    titleEnglish: "Tenses & Voice (Active & Passive)",
    section: "8. General English",
    subSection: "English Grammar",
    isCommon: false,
    commonNotes: "CET विशेष विषय।",
    examScope: "CET",
  },
  {
    id: "cet-eng-2",
    titleHindi: "Narration (Direct & Indirect), Use of Prepositions & Articles",
    titleEnglish: "Narration, Prepositions & Articles",
    section: "8. General English",
    subSection: "English Grammar",
    isCommon: false,
    commonNotes: "CET विशेष विषय।",
    examScope: "CET",
  },
  {
    id: "cet-eng-3",
    titleHindi: "Synonyms, Antonyms, One Word Substitution & Idioms/Phrases",
    titleEnglish: "Vocabulary: Synonyms, Antonyms, One Word & Idioms",
    section: "8. General English",
    subSection: "Vocabulary",
    isCommon: false,
    commonNotes: "CET विशेष विषय।",
    examScope: "CET",
  },
  {
    id: "cet-eng-4",
    titleHindi: "Comprehension of an Unseen Passage",
    titleEnglish: "Reading Comprehension",
    section: "8. General English",
    subSection: "Comprehension",
    isCommon: false,
    commonNotes: "CET विशेष विषय।",
    examScope: "CET",
  },
  {
    id: "cet-eng-5",
    titleHindi: "Glossary of Official/Technical Terms & Letter Writing formats",
    titleEnglish: "Technical Glossary & Official Correspondence",
    section: "8. General English",
    subSection: "Official Terms",
    isCommon: false,
    commonNotes: "CET विशेष विषय।",
    examScope: "CET",
  },

  // विषय 9: कंप्यूटर का बुनियादी ज्ञान (Basic Computer Knowledge)
  {
    id: "cet-comp-1",
    titleHindi: "कंप्यूटर की विशेषताएं, कंप्यूटर संगठन (RAM, ROM, File System, I/O Devices)",
    titleEnglish: "Characteristics of Computers, CPU, RAM, ROM, Storage & Devices",
    section: "9. कंप्यूटर का बुनियादी ज्ञान (Basic Computer)",
    subSection: "हार्डवेयर एवं मूल अवधारणाएं",
    isCommon: false,
    commonNotes: "CET विशेष विषय (Senior Teacher Paper-1 में नहीं है)।",
    examScope: "CET",
  },
  {
    id: "cet-comp-2",
    titleHindi: "ऑपरेटिंग सिस्टम एवं फाइल मैनेजमेंट (Operating Systems & File Handling)",
    titleEnglish: "Operating Systems, File Formats & GUI",
    section: "9. कंप्यूटर का बुनियादी ज्ञान (Basic Computer)",
    subSection: "सॉफ्टवेयर एवं ओएस",
    isCommon: false,
    commonNotes: "CET विशेष विषय।",
    examScope: "CET",
  },
  {
    id: "cet-comp-3",
    titleHindi: "एमएस ऑफिस का व्यावहारिक ज्ञान: MS Word, MS Excel, MS PowerPoint",
    titleEnglish: "MS Office Suite: MS Word, MS Excel, MS PowerPoint",
    section: "9. कंप्यूटर का बुनियादी ज्ञान (Basic Computer)",
    subSection: "एमएस ऑफिस",
    isCommon: false,
    commonNotes: "CET विशेष विषय।",
    examScope: "CET",
  },

  // विषय 10: समसामयिक घटनाएं (Current Affairs)
  {
    id: "cet-curr-1",
    titleHindi: "राजस्थान, राष्ट्रीय एवं अंतरराष्ट्रीय समसामयिक घटनाएं व वर्तमान मुद्दे",
    titleEnglish: "Current Events & Issues: Rajasthan, National & International",
    section: "10. समसामयिक घटनाएं (Current Affairs)",
    subSection: "समसामयिकी",
    isCommon: true,
    commonKey: "curr-persons-places",
    commonNotes: "वरिष्ठ अध्यापक Paper-1 खंड-II से पूर्णतः कॉमन है।",
    examScope: "BOTH",
  },
  {
    id: "cet-curr-2",
    titleHindi: "वर्तमान में चर्चित व्यक्ति, स्थान, संस्थाएं एवं पुरस्कार",
    titleEnglish: "Persons, Places, Institutions & Awards in News",
    section: "10. समसामयिक घटनाएं (Current Affairs)",
    subSection: "समसामयिकी",
    isCommon: true,
    commonKey: "curr-awards-books",
    commonNotes: "वरिष्ठ अध्यापक समसामयिकी में भी प्रमुख व्यक्ति व पुरस्कार शामिल हैं।",
    examScope: "BOTH",
  },
  {
    id: "cet-curr-3",
    titleHindi: "खेलकूद गतिविधियां, राष्ट्रीय एवं राज्य स्तरीय प्रतियोगिताएं व पदक",
    titleEnglish: "Sports & Games: National & Rajasthan State Events",
    section: "10. समसामयिक घटनाएं (Current Affairs)",
    subSection: "खेलकूद",
    isCommon: true,
    commonKey: "curr-sports",
    commonNotes: "वरिष्ठ अध्यापक Paper-1 के खेलकूद खंड से शत-प्रतिशत कॉमन है।",
    examScope: "BOTH",
  },
];

// ─────────────────────────────────────────────────────────────────────────────
// 3. Merged Common Topics Structure
// ─────────────────────────────────────────────────────────────────────────────
export interface MergedCommonTopic {
  commonKey: string;
  category: string;
  categoryHindi: string;
  titleHindi: string;
  titleEnglish: string;
  seniorTeacherTopic: SyllabusTopicItem;
  cetTopic: SyllabusTopicItem;
  canonicalTopicId?: number;
  canonicalTopicName?: string;
  coverageBenefit: string; // How preparing this helps in both exams
}

export function getMergedCommonTopics(): MergedCommonTopic[] {
  const commonMap = new Map<string, { st?: SyllabusTopicItem; cet?: SyllabusTopicItem }>();

  for (const st of SENIOR_TEACHER_SYLLABUS) {
    if (st.commonKey) {
      if (!commonMap.has(st.commonKey)) commonMap.set(st.commonKey, {});
      commonMap.get(st.commonKey)!.st = st;
    }
  }

  for (const cet of CET_SYLLABUS) {
    if (cet.commonKey) {
      if (!commonMap.has(cet.commonKey)) commonMap.set(cet.commonKey, {});
      commonMap.get(cet.commonKey)!.cet = cet;
    }
  }

  const results: MergedCommonTopic[] = [];

  for (const [key, pair] of commonMap.entries()) {
    if (pair.st && pair.cet) {
      let category = "Rajasthan GK";
      let categoryHindi = "राजस्थान सामान्य ज्ञान";

      if (key.startsWith("raj-geo")) {
        category = "Rajasthan Geography";
        categoryHindi = "राजस्थान का भूगोल";
      } else if (key.startsWith("raj-hist")) {
        category = "Rajasthan History";
        categoryHindi = "राजस्थान का इतिहास";
      } else if (key.startsWith("raj-cult")) {
        category = "Rajasthan Art & Culture";
        categoryHindi = "राजस्थान कला एवं संस्कृति";
      } else if (key.startsWith("raj-pol")) {
        category = "Rajasthan Polity & Admin";
        categoryHindi = "राजस्थान राजनीतिक एवं प्रशासनिक व्यवस्था";
      } else if (key.startsWith("ind-geo")) {
        category = "India Geography";
        categoryHindi = "भारत का भूगोल";
      } else if (key.startsWith("ind-pol")) {
        category = "Indian Polity & Constitution";
        categoryHindi = "भारतीय संविधान एवं राजव्यवस्था";
      } else if (key.startsWith("ind-eco")) {
        category = "Indian Economy";
        categoryHindi = "भारतीय अर्थव्यवस्था";
      } else if (key.startsWith("curr")) {
        category = "Current Affairs";
        categoryHindi = "समसामयिक घटनाक्रम";
      } else if (key.startsWith("env")) {
        category = "Environment & Ecology";
        categoryHindi = "पर्यावरण एवं पारिस्थितिकी";
      }

      results.push({
        commonKey: key,
        category,
        categoryHindi,
        titleHindi: pair.st.titleHindi,
        titleEnglish: pair.st.titleEnglish,
        seniorTeacherTopic: pair.st,
        cetTopic: pair.cet,
        canonicalTopicId: pair.st.canonicalTopicId ?? pair.cet.canonicalTopicId,
        canonicalTopicName: pair.st.canonicalTopicName ?? pair.cet.canonicalTopicName,
        coverageBenefit:
          "इसे एक बार तैयार करने पर वरिष्ठ अध्यापक पेपर-1 और CET दोनों परीक्षाओं में पूर्ण अंक भार मिलता है।",
      });
    }
  }

  return results;
}
